"""2026-09-05全96課題の再計画。本文・進捗案・購入/印刷参照の個別記録。

ORIGINAL_METADATA は見直し前の依存差分を出すためにも保持する。
REVIEW の各行は 現在地、次作業、完了証拠、購入項目、印刷節、根拠、進捗の順。
"""

ORIGINAL_METADATA = [{'key': 'E1',
  'title': 'E1 [エピック] 準備 — 棚卸し・サーボ実測・config 確定',
  'parent': None,
  'milestone': 'M0 準備完了',
  'labels': ['type/エピック', 'area/運営', 'prio/P0'],
  'blocked_by': []},
 {'key': 'E2',
  'title': 'E2 [エピック] 印刷キュー — X2D は 1 台なので順番待ち',
  'parent': None,
  'milestone': None,
  'labels': ['type/エピック', 'area/印刷', 'res/プリンタ'],
  'blocked_by': []},
 {'key': 'E3',
  'title': 'E3 [エピック] 電装・電源・ファームウェア (ベンチ)',
  'parent': None,
  'milestone': 'M0 準備完了',
  'labels': ['type/エピック', 'area/電装', 'prio/P0'],
  'blocked_by': []},
 {'key': 'E4',
  'title': 'E4 [エピック] 脚・歩行 — 片脚ゲート → 4 脚 → 頭無し歩行',
  'parent': None,
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/エピック', 'area/組立', 'prio/P0'],
  'blocked_by': []},
 {'key': 'E5',
  'title': 'E5 [エピック] 腕 (左右) — 骨格チェーン → 吊り下げ → シェル',
  'parent': None,
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/エピック', 'area/組立', 'prio/P1'],
  'blocked_by': []},
 {'key': 'E6',
  'title': 'E6 [エピック] 頭部 — 目ポッド・カメラ目・音声ユニット',
  'parent': None,
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/エピック', 'area/組立', 'prio/P1'],
  'blocked_by': []},
 {'key': 'E7',
  'title': 'E7 [エピック] 意匠シェル・Cabin・仕上げ (フルドレス)',
  'parent': None,
  'milestone': 'M4 フルドレス',
  'labels': ['type/エピック', 'area/仕上げ', 'prio/P1'],
  'blocked_by': []},
 {'key': 'E8',
  'title': 'E8 [エピック] 統合・調整・完成',
  'parent': None,
  'milestone': 'M5 統合・完成',
  'labels': ['type/エピック', 'area/試験', 'prio/P1'],
  'blocked_by': []},
 {'key': 'P-01',
  'title': 'P-01 [運営] 購入部品の棚卸し・検品 (BOM / shopping.md D-1 と照合)',
  'parent': 'E1',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/運営', 'area/測定', '並行作業OK', 'prio/P0', 'good first issue'],
  'blocked_by': []},
 {'key': 'P-02',
  'title': 'P-02 [運営] 印刷済みパーツの棚卸し・検品・ラベリング (旧 rev 混入チェック)',
  'parent': 'E1',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/運営', 'area/印刷', '並行作業OK', 'prio/P0', 'good first issue'],
  'blocked_by': []},
 {'key': 'P-03',
  'title': 'P-03 [測定] サーボ・ホーン実測 (STD ×14 / MG90S ×6 / ES9251II ×3) → 実測表',
  'parent': 'E1',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/測定', '並行作業OK', 'prio/P0'],
  'blocked_by': []},
 {'key': 'P-04',
  'title': 'P-04 [CAD] config.py を実測値へ更新 → STL 再生成 → 全チェッカー緑 → 影響パーツ判定',
  'parent': 'E1',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/CAD', 'skill/CAD-Python', 'prio/P0'],
  'blocked_by': ['P-03']},
 {'key': 'P-05',
  'title': 'P-05 [要判断] 印刷済み骨格 (chassis / coxa×4 / femur×4 / arm_pod) の再印刷要否',
  'parent': 'E1',
  'milestone': 'M0 準備完了',
  'labels': ['type/要判断', 'area/印刷', 'prio/P0'],
  'blocked_by': ['P-04']},
 {'key': 'P-06',
  'title': 'P-06 [測定] 音声ユニット部品の実測 (INMP441 基板 / φ20 SPK 厚) → AUDIO_* 更新 → check_audio',
  'parent': 'E1',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/測定', 'area/CAD', '並行作業OK', 'prio/P1'],
  'blocked_by': []},
 {'key': 'P-07',
  'title': 'P-07 [測定] カメラモジュール確認 (XIAO ESP32S3 Sense: センサー型番・子基板寸法・FOV) → CAM2_* 更新 → check_camera',
  'parent': 'E1',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/測定', 'area/CAD', '並行作業OK', 'prio/P1'],
  'blocked_by': []},
 {'key': 'P-08',
  'title': 'P-08 [運営] イシュー運用の立ち上げ (CONTRIBUTING / テンプレ / Project ボード / 協力者招待)',
  'parent': 'E1',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/運営', 'prio/P1'],
  'blocked_by': []},
 {'key': 'PR-01',
  'title': 'PR-01 [印刷] PLA_Matte_Gray_2 — キット灰意匠 21 種 36 個 (70g / 3.7h, A3 灰)',
  'parent': 'E2',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P1'],
  'blocked_by': []},
 {'key': 'PR-02',
  'title': 'PR-02 [印刷] PLA_Black_1 — トゥ×12 + 指×6 + Insert×12 (34g / 2.2h, 黒へ差替)',
  'parent': 'E2',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P1'],
  'blocked_by': []},
 {'key': 'PR-03',
  'title': 'PR-03 [印刷] PLA_Red_1 — 赤ランプ 大×4 小×4 (2.5g, 赤へ差替 or 白+赤塗装)',
  'parent': 'E2',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P2'],
  'blocked_by': []},
 {'key': 'PR-04',
  'title': 'PR-04 [印刷] 片脚試験用の標準 tibia_link ×1 を先に印刷する',
  'parent': 'E2',
  'milestone': 'M1 片脚 Go/No-Go',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P0'],
  'blocked_by': ['P-04', 'P-05']},
 {'key': 'PR-05',
  'title': 'PR-05 [印刷] PLA_Matte_Gray — leg_foot_bored ×4 + thigh_cap ×4 (Mouth 2 点は除外, A3 灰)',
  'parent': 'E2',
  'milestone': 'M1 片脚 Go/No-Go',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P0'],
  'blocked_by': ['P-04']},
 {'key': 'PR-06',
  'title': 'PR-06 [印刷] PETG_Walk_4_Rest — pod_neck + 腕骨格 ×2 + eye_carrier ×2 + camera_carrier + claw_mount '
           '×2 + spk (84g / 5.2h)',
  'parent': 'E2',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P1'],
  'blocked_by': ['P-04', 'P-07', 'RV-10', 'RV-09', 'RV-15']},
 {'key': 'PR-07',
  'title': 'PR-07 [印刷] Mouth_Cannon_Bored + Mouth_Ball_Bored (+ Neck / mic クレードルは変更時のみ)',
  'parent': 'E2',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P1'],
  'blocked_by': ['P-06', 'RV-08']},
 {'key': 'PR-08',
  'title': 'PR-08 [印刷] Head_Top_Eyecut v2 単体 (青 64g) — v1 が印刷済みなら差し替え',
  'parent': 'E2',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P1'],
  'blocked_by': ['P-02', 'RV-09']},
 {'key': 'PR-09',
  'title': 'PR-09 [印刷] (条件付き) 骨格の再印刷 — P-05 で「再印刷」と決まった部品のみ',
  'parent': 'E2',
  'milestone': 'M1 片脚 Go/No-Go',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P0'],
  'blocked_by': ['P-05']},
 {'key': 'PR-10',
  'title': 'PR-10 [印刷] eye_pod_camera_base 再印刷 (白 5g) — 印刷済み品は旧 rev (ポケット壁 ~1mm 違い)',
  'parent': 'E2',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'skill/プリンタ操作', 'prio/P1'],
  'blocked_by': []},
 {'key': 'EL-01',
  'title': 'EL-01 [電装] 電源系ベンチ組立 (LiPo→ヒューズ→SW→UBEC 6V / DC-DC 5V, バスバー, コンデンサ, 分圧)',
  'parent': 'E3',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/電装', 'skill/はんだ', '並行作業OK', 'prio/P0'],
  'blocked_by': []},
 {'key': 'EL-02',
  'title': 'EL-02 [電装] PCA9685 ×2 準備 (board1 A0 ジャンパ→0x41, ヘッダ実装規約) + ESP32 I2C 疎通',
  'parent': 'E3',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/電装', 'skill/はんだ', '並行作業OK', 'prio/P0'],
  'blocked_by': []},
 {'key': 'EL-03',
  'title': 'EL-03 [ファーム] CALIBRATION_MODE ビルド + ESP32 書き込み + AP 接続確認',
  'parent': 'E3',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/ファーム', 'skill/ファーム', '並行作業OK', 'prio/P0'],
  'blocked_by': []},
 {'key': 'EL-04',
  'title': 'EL-04 [電装] 全サーボの中立化 (1500µs) とマーキング (STD ×14 / MG90S ×6 / ES9251II ×3)',
  'parent': 'E3',
  'milestone': 'M0 準備完了',
  'labels': ['type/タスク', 'area/電装', 'prio/P0'],
  'blocked_by': ['EL-01', 'EL-02', 'EL-03']},
 {'key': 'EL-05',
  'title': 'EL-05 [配線] 脚サーボハーネス ×12 製作 (電源 AWG20→AWG16 バス分岐 / 信号 AWG26→PCA)',
  'parent': 'E3',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/配線', 'skill/はんだ', '並行作業OK', 'prio/P1'],
  'blocked_by': []},
 {'key': 'EL-06',
  'title': 'EL-06 [配線] 腕・目サーボハーネス製作 (MG90S ×6 / ES9251II ×2, AWG26/30)',
  'parent': 'E3',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/配線', 'skill/はんだ', '並行作業OK', 'prio/P1'],
  'blocked_by': []},
 {'key': 'EL-07',
  'title': 'EL-07 [ファーム] 本番ビルド (CALIBRATION_MODE 解除, JOINT_SIGN/ARM_SIGN 確認) + 書き込み + Web UI 動作',
  'parent': 'E3',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/ファーム', 'skill/ファーム', 'prio/P0'],
  'blocked_by': ['EL-03', 'P-04']},
 {'key': 'EL-08',
  'title': 'EL-08 [電装] WS2812 ×12 + 74AHCT125 + DFPlayer (+microSD 音源) のベンチ配線・点灯/再生確認',
  'parent': 'E3',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/電装', 'skill/はんだ', '並行作業OK', 'prio/P2'],
  'blocked_by': ['EL-07']},
 {'key': 'L-01',
  'title': 'L-01 [組立] 脚 FL (標準版) を組む — 片脚ゲート用の 1 本目',
  'parent': 'E4',
  'milestone': 'M1 片脚 Go/No-Go',
  'labels': ['type/タスク', 'area/組立', 'prio/P0'],
  'blocked_by': ['PR-04', 'PR-05', 'EL-04', 'P-05']},
 {'key': 'L-02',
  'title': 'L-02 [ゲート] 片脚ベンチ試験 — 1.2kg×レバー155mm (=18.6kgf·cm) 保持 (6V) / スイープ / 保持電流',
  'parent': 'E4',
  'milestone': 'M1 片脚 Go/No-Go',
  'labels': ['type/ゲート', 'area/試験', 'area/測定', 'prio/P0'],
  'blocked_by': ['L-01', 'EL-01', 'EL-03']},
 {'key': 'L-03',
  'title': 'L-03 [組立] 脚 FR (ミラー版 `_m`) を組む',
  'parent': 'E4',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/組立', '並行作業OK', 'prio/P0'],
  'blocked_by': ['L-02', 'PR-11']},
 {'key': 'L-04',
  'title': 'L-04 [組立] 脚 RL (ミラー版 `_m`) を組む',
  'parent': 'E4',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/組立', '並行作業OK', 'prio/P0'],
  'blocked_by': ['L-02', 'PR-11']},
 {'key': 'L-05',
  'title': 'L-05 [組立] 脚 RR (標準版) を組む',
  'parent': 'E4',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/組立', '並行作業OK', 'prio/P0'],
  'blocked_by': ['L-02', 'PR-11']},
 {'key': 'L-06',
  'title': 'L-06 [組立] シャーシ電装組付け (ヨーサーボ ×4 / PCA スタック / ESP32 / UBEC / DC-DC / SW / battery_cradle)',
  'parent': 'E4',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/組立', 'area/電装', 'res/本体', 'prio/P0'],
  'blocked_by': ['EL-01', 'EL-02', 'EL-04', 'P-05']},
 {'key': 'L-07',
  'title': 'L-07 [組立] 4 脚をシャーシへ取付 (ヨーホーン共締め, 方位 FR15/FL165/RL210/RR330)',
  'parent': 'E4',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/組立', 'res/本体', 'prio/P0'],
  'blocked_by': ['L-01', 'L-03', 'L-04', 'L-05', 'L-06']},
 {'key': 'L-08',
  'title': 'L-08 [配線] 脚 12ch 本体配線 (経路・束ね・バス直結・PCA ch 割当)',
  'parent': 'E4',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/配線', 'skill/はんだ', 'res/本体', 'prio/P0'],
  'blocked_by': ['L-07', 'EL-05']},
 {'key': 'L-09',
  'title': 'L-09 [試験] 通電・中立確認・トリム (サーボ未接続電圧 → 1 本 → 全数 → Web UI Trim)',
  'parent': 'E4',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/試験', 'res/本体', 'prio/P0'],
  'blocked_by': ['L-08', 'EL-07']},
 {'key': 'L-10',
  'title': 'L-10 [ゲート] 頭無し歩行試験 — 立位→前進→旋回→停止, 転倒なし, 電流・電圧ログ',
  'parent': 'E4',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/ゲート', 'area/試験', 'area/測定', 'prio/P0'],
  'blocked_by': ['L-09']},
 {'key': 'EL-09',
  'title': 'EL-09 [要判断] UBEC 定格 (連続 10A) の妥当性 — L-10 の実測電流で 15〜20A 級への変更を判断',
  'parent': 'E3',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/要判断', 'area/電装', 'prio/P1'],
  'blocked_by': []},
 {'key': 'EL-10',
  'title': 'EL-10 [ファーム] アイドル時の発熱対策 — 一定時間無指令で休止姿勢 / 段階脱力 (S-07)',
  'parent': 'E3',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/ファーム', 'skill/ファーム', '並行作業OK', 'prio/P2'],
  'blocked_by': ['EL-07']},
 {'key': 'L-11',
  'title': 'L-11 [要判断] 股ピッチの実力を測り、低トルク歩容・軽量化・6V対応品を比較する',
  'parent': 'E4',
  'milestone': 'M1 片脚 Go/No-Go',
  'labels': ['type/要判断', 'area/試験', 'area/電装', 'prio/P0'],
  'blocked_by': []},
 {'key': 'A-01',
  'title': 'A-01 [組立] 右腕チェーンをベンチで組む (肩ブラケット→上腕→前腕→固定爪)',
  'parent': 'E5',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/組立', 'skill/模型仕上げ', '並行作業OK', 'prio/P1'],
  'blocked_by': ['PR-06', 'PR-01', 'PR-02', 'EL-04', 'RV-10', 'RV-17']},
 {'key': 'A-02',
  'title': 'A-02 [組立] 左腕チェーンをベンチで組む (_L パーツ)',
  'parent': 'E5',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/組立', 'skill/模型仕上げ', '並行作業OK', 'prio/P1'],
  'blocked_by': ['PR-06', 'PR-01', 'PR-02', 'EL-04', 'RV-10', 'RV-17']},
 {'key': 'A-03',
  'title': 'A-03 [組立] 肩ヨーサーボ ×2 をシャーシへ + 両腕を吊り下げ + 配線 + ベンチ確認 (TUCK/READY/REACH/WAVE)',
  'parent': 'E5',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/組立', 'area/配線', 'res/本体', 'prio/P1'],
  'blocked_by': ['A-01', 'A-02', 'L-06', 'EL-06', 'EL-07']},
 {'key': 'A-04',
  'title': 'A-04 [仕上げ] 腕シェル被せ (arm_pod 上下 ×2 / elbow_shell ×2 / Arm Guard 左右)',
  'parent': 'E5',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/仕上げ', 'skill/模型仕上げ', 'prio/P2'],
  'blocked_by': ['A-03']},
 {'key': 'H-01',
  'title': 'H-01 [組立] 目ポッド ×2 (キョロキョロ) — ドット黒仕上げ / ES9251II / ホーン先付け / 中立位相',
  'parent': 'E6',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/組立', 'skill/模型仕上げ', '並行作業OK', 'prio/P1'],
  'blocked_by': ['PR-06', 'EL-04']},
 {'key': 'H-02',
  'title': 'H-02 [組立] カメラ目 — 子基板→camera_carrier→base→shell 接着, XIAO ファーム + WiFi 静止画疎通',
  'parent': 'E6',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/組立', 'area/ファーム', 'skill/ファーム', '並行作業OK', 'prio/P1'],
  'blocked_by': ['P-07', 'PR-06', 'PR-10']},
 {'key': 'H-03',
  'title': 'H-03 [組立] 音声ユニット組込 — INMP441→cradle_mic 圧入 / φ20 SPK / cradle_spk / 8 芯を Neck・Ball ボアへ',
  'parent': 'E6',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/組立', 'skill/はんだ', '並行作業OK', 'prio/P1'],
  'blocked_by': ['PR-07', 'PR-06', 'P-02', 'RV-08']},
 {'key': 'H-04',
  'title': 'H-04 [電装] MAX98357A + I2S ベンチ配線 → voice_bridge --mock で PTT 録音 / 440Hz 再生を確認',
  'parent': 'E6',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/電装', 'area/ファーム', 'skill/はんだ', 'prio/P1'],
  'blocked_by': ['H-03', 'EL-07']},
 {'key': 'H-05',
  'title': 'H-05 [組立] Mouth 一式 (Ball→Neck→Cannon チェーン + Cap/Key/Peg) をキット標準で組む',
  'parent': 'E6',
  'milestone': 'M3 サブアセンブリ',
  'labels': ['type/タスク', 'area/組立', 'skill/模型仕上げ', '並行作業OK', 'prio/P1'],
  'blocked_by': ['H-03', 'PR-01', 'RV-08']},
 {'key': 'H-06',
  'title': 'H-06 [CAD] Cabin内部の電装室・基板保持・挿入経路・配線を成立させる',
  'parent': 'E6',
  'milestone': 'M4 フルドレス',
  'labels': ['type/不具合', 'area/CAD', 'area/電装', 'prio/P0', '並行作業OK'],
  'blocked_by': []},
 {'key': 'H-07',
  'title': 'H-07 [要判断] CH_HEAD (ch12) の扱い — 駆動対象が実在しない (推奨: 予備維持)',
  'parent': 'E6',
  'milestone': 'M5 統合・完成',
  'labels': ['type/要判断', 'area/ファーム', 'prio/P2'],
  'blocked_by': []},
 {'key': 'S-01',
  'title': 'S-01 [組立] pod_neck 取付 + TailJoint (青コーン+Ball リング) 化粧スリーブ接着',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/組立', 'res/本体', 'prio/P1'],
  'blocked_by': ['PR-06', 'PR-01', 'L-06', 'RV-15', 'RV-07']},
 {'key': 'S-02a',
  'title': 'S-02a [仕上げ] 脚 FL の装飾 — thigh_cap / Thigh_Guard / shin_shell (標準) / Shin_Guard / Leg_Toe ×3',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/仕上げ', 'skill/模型仕上げ', '並行作業OK', 'prio/P2'],
  'blocked_by': ['L-10', 'PR-05', 'PR-01', 'PR-02', 'RV-06', 'RV-14', 'RV-16']},
 {'key': 'S-02b',
  'title': 'S-02b [仕上げ] 脚 FR の装飾 — thigh_cap / Thigh_Guard / shin_shell_m (ミラー) / Shin_Guard / Leg_Toe ×3',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/仕上げ', 'skill/模型仕上げ', '並行作業OK', 'prio/P2'],
  'blocked_by': ['L-10', 'PR-05', 'PR-01', 'PR-02', 'RV-06', 'RV-14', 'RV-16']},
 {'key': 'S-02c',
  'title': 'S-02c [仕上げ] 脚 RL の装飾 — thigh_cap / Thigh_Guard / shin_shell_m (ミラー) / Shin_Guard / Leg_Toe ×3',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/仕上げ', 'skill/模型仕上げ', '並行作業OK', 'prio/P2'],
  'blocked_by': ['L-10', 'PR-05', 'PR-01', 'PR-02', 'RV-06', 'RV-14', 'RV-16']},
 {'key': 'S-02d',
  'title': 'S-02d [仕上げ] 脚 RR の装飾 — thigh_cap / Thigh_Guard / shin_shell (標準) / Shin_Guard / Leg_Toe ×3',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/仕上げ', 'skill/模型仕上げ', '並行作業OK', 'prio/P2'],
  'blocked_by': ['L-10', 'PR-05', 'PR-01', 'PR-02', 'RV-06', 'RV-14', 'RV-16']},
 {'key': 'S-03',
  'title': 'S-03 [組立] 頭部組立 — Head_Bottom_Armcut / 目ポッド ×2 + カメラ目装着 / Head 装飾 / Head_Top 被せ',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/組立', 'area/仕上げ', 'res/本体', 'prio/P1'],
  'blocked_by': ['H-01', 'H-02', 'H-06', 'PR-08', 'PR-01', 'PR-02', 'L-10', 'RV-09', 'RV-13']},
 {'key': 'S-04',
  'title': 'S-04 [組立] Mouth 一式を頭部ソケットへ取付 (Ball スナップ, -18° 下向きポーズ, 配線 φ7 穴→MAX98357A)',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/組立', 'res/本体', 'prio/P1'],
  'blocked_by': ['H-05', 'S-03']},
 {'key': 'S-05',
  'title': 'S-05 [仕上げ] Cabin (背中ポッド) をキット標準で組む — Front/Back/Turret/RedLight/Spinnarette/Insert/Cabin_Eye + '
           'LED 仕込み',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/仕上げ', 'skill/模型仕上げ', '並行作業OK', 'prio/P1', 'good first issue', 'help wanted'],
  'blocked_by': ['PR-01', 'PR-02', 'PR-03', 'H-06', 'RV-15']},
 {'key': 'S-06',
  'title': 'S-06 [組立] Cabin を pod_neck へ取付 (フランジ M3×4 現物合わせ穴あけ, LED 配線を梁沿いにシャーシへ)',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/組立', 'res/本体', 'skill/模型仕上げ', 'prio/P1'],
  'blocked_by': ['S-05', 'S-01']},
 {'key': 'S-07',
  'title': 'S-07 [電装] LED ×12 / DFPlayer / 74AHCT125 を本体へ組込 (直列順 0→11, 目 LED は carrier 裏)',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/タスク', 'area/電装', 'area/配線', 'skill/はんだ', 'res/本体', 'prio/P2'],
  'blocked_by': ['EL-08', 'S-03', 'S-06']},
 {'key': 'S-08',
  'title': 'S-08 [要判断] Head_Insert_Black ×4 のうち 2 個の位置 (3MF に座標無し → 実物写真で確定)',
  'parent': 'E7',
  'milestone': 'M4 フルドレス',
  'labels': ['type/要判断', 'area/仕上げ', 'prio/P2'],
  'blocked_by': []},
 {'key': 'I-01',
  'title': 'I-01 [測定] 実重量計測・重心確認 (対角 2 脚持ち上げ, バッテリー位置調整, 3.0kg 想定と比較)',
  'parent': 'E8',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/測定', 'area/試験', 'res/本体', 'prio/P1'],
  'blocked_by': ['S-03', 'S-06', 'A-04', 'S-02a', 'S-02b', 'S-02c', 'S-02d']},
 {'key': 'I-02',
  'title': 'I-02 [試験] フルドレス歩行調整 (Trim / 体高 115・歩幅 50% から / 腕 TUCK / foot_pad 滑り / 電流電圧ログ)',
  'parent': 'E8',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/試験', 'area/測定', 'res/本体', 'prio/P1'],
  'blocked_by': ['I-01', 'RV-06', 'RV-07']},
 {'key': 'I-03',
  'title': 'I-03 [ファーム] 音声会話の実運用 (iPhone テザリング 2.4GHz / STA 設定 / mDNS / API キー / voice_bridge)',
  'parent': 'E8',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/ファーム', 'skill/ファーム', 'prio/P1'],
  'blocked_by': ['H-04', 'S-04']},
 {'key': 'I-04',
  'title': 'I-04 [ファーム] カメラ連携 (voice_bridge --camera-url で「見て」に答える)',
  'parent': 'E8',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/ファーム', 'skill/ファーム', 'prio/P2'],
  'blocked_by': ['H-02', 'I-03']},
 {'key': 'I-05',
  'title': 'I-05 [試験] 演出確認 — 目 (KYORO/FRONT/SCAN + 歩行方向バイアス) / LED / DFPlayer 起動音',
  'parent': 'E8',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/試験', 'prio/P2'],
  'blocked_by': ['S-07', 'I-02']},
 {'key': 'I-06',
  'title': 'I-06 [ドキュメント] 組立で得た現物合わせ知見を docs へ反映 (assembly / wiring / print_manifest / HANDOFF)',
  'parent': 'E8',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/ドキュメント', '並行作業OK', 'prio/P2'],
  'blocked_by': []},
 {'key': 'I-08',
  'title': 'I-08 [検証] 実制御・実ケース・材料別接触で物理シミュレーションを検証する',
  'parent': 'E8',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/ファーム', 'skill/CAD-Python', '並行作業OK', 'prio/P0'],
  'blocked_by': []},
 {'key': 'I-07',
  'title': 'I-07 [運営] 完成お披露目 — 写真・動画・README 更新',
  'parent': 'E8',
  'milestone': 'M5 統合・完成',
  'labels': ['type/タスク', 'area/ドキュメント', 'prio/P2'],
  'blocked_by': ['I-02', 'I-03', 'I-05']},
 {'key': 'PR-11',
  'title': 'PR-11 [印刷] 片脚合格後に残りのtibiaを標準1本・ミラー2本印刷する',
  'parent': 'E2',
  'milestone': 'M2 頭無し歩行',
  'labels': ['type/タスク', 'area/印刷', 'res/プリンタ', 'prio/P0'],
  'blocked_by': ['L-02']},
 {'key': 'E9',
  'title': 'E9 [監査] 実機製作前提を独立検証し、修正と実機確認を切り分ける',
  'parent': None,
  'milestone': None,
  'labels': ['type/エピック', 'area/試験', 'prio/P0'],
  'blocked_by': []},
 {'key': 'RV-01',
  'title': 'RV-01 [不具合] 操作画面・低電圧停止・腕脚ガードを修正して回帰検証する',
  'parent': 'E9',
  'milestone': None,
  'labels': ['type/不具合', 'area/ファーム', 'prio/P0', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-02',
  'title': 'RV-02 [検証] 現物3MFの形状・数量・材質と再生成時の保持を検査する',
  'parent': 'E9',
  'milestone': None,
  'labels': ['type/不具合', 'area/印刷', 'area/CAD', 'prio/P0', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-03',
  'title': 'RV-03 [不具合] 幾何・歩容検査のNGと計算失敗を終了コードへ反映する',
  'parent': 'E9',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'area/試験', 'prio/P0'],
  'blocked_by': []},
 {'key': 'RV-04',
  'title': 'RV-04 [不具合] Issue同期で進捗を保持し、重複と依存関係を検証する',
  'parent': 'E9',
  'milestone': None,
  'labels': ['type/不具合', 'area/運営', 'prio/P1', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-05',
  'title': 'RV-05 [ゲート] 修正後の全検証と未確認の実機条件を記録する',
  'parent': 'E9',
  'milestone': None,
  'labels': ['type/ゲート', 'area/試験', 'prio/P0'],
  'blocked_by': ['RV-01',
                 'RV-02',
                 'RV-03',
                 'RV-04',
                 'I-08',
                 'RV-08',
                 'RV-09',
                 'RV-10',
                 'RV-11',
                 'RV-12',
                 'RV-13',
                 'RV-14',
                 'RV-15',
                 'RV-16',
                 'RV-17',
                 'H-06']},
 {'key': 'RV-06',
  'title': 'RV-06 [機構不具合] トゥと硬い足本体の先行接地を解消して足裏支持を成立させる',
  'parent': 'E4',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'area/試験', 'prio/P0'],
  'blocked_by': []},
 {'key': 'RV-07',
  'title': 'RV-07 [試験] 実際の壁数・充填率による脚とポッド支持の強度を確かめる',
  'parent': 'E7',
  'milestone': None,
  'labels': ['type/ゲート', 'area/測定', 'area/印刷', 'prio/P0'],
  'blocked_by': []},
 {'key': 'RV-08',
  'title': 'RV-08 [機構不具合] マイクの挿入経路とBall–Neckの実体干渉を直す',
  'parent': 'E6',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'prio/P0', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-09',
  'title': 'RV-09 [機構不具合] 頭部内の実サーボケースとポッド梁の干渉を解消する',
  'parent': 'E7',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'prio/P0', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-10',
  'title': 'RV-10 [機構不具合] 腕と脚の隣接部品同士の自己干渉を取り除く',
  'parent': 'E5',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'prio/P0', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-11',
  'title': 'RV-11 [電装] 部品の実型番・電源収支・停止回路・測定手順を整合させる',
  'parent': 'E3',
  'milestone': None,
  'labels': ['type/不具合', 'area/電装', 'area/ドキュメント', 'prio/P0', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-12',
  'title': 'RV-12 [検証] 表示用モデルと全ファイルの検査記録を実設計に合わせる',
  'parent': 'E9',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'area/ドキュメント', 'prio/P1', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-13',
  'title': 'RV-13 [機構不具合] 頭の7固定穴から外殻へ届く支持柱・受け座を設計する',
  'parent': 'E7',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'prio/P0'],
  'blocked_by': ['RV-09']},
 {'key': 'RV-14',
  'title': 'RV-14 [機構不具合] シャーシと大腿カバーの実交差を解消する',
  'parent': 'E4',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'prio/P0'],
  'blocked_by': ['RV-09']},
 {'key': 'RV-15',
  'title': 'RV-15 [機構不具合] 首・Cabin・装飾を全長で組み合わせ、支持と挿入を成立させる',
  'parent': 'E7',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'prio/P0', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-16',
  'title': 'RV-16 [機構不具合] 大腿・脛ガードの受け座と実際に入る組立経路を作る',
  'parent': 'E7',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'prio/P1', '並行作業OK'],
  'blocked_by': []},
 {'key': 'RV-17',
  'title': 'RV-17 [機構不具合] 固定爪・指・指飾りの嵌合公差と接着座を検証する',
  'parent': 'E5',
  'milestone': None,
  'labels': ['type/不具合', 'area/CAD', 'prio/P1', '並行作業OK'],
  'blocked_by': []}]

LABELS = [('type/エピック', '5319e7', '作業ストリームの親イシュー。サブイシューで子を束ねる'),
 ('type/ゲート', 'b60205', 'Go/No-Go 判定。合格するまで下流へ進まない'),
 ('type/タスク', '0e8a16', '1 人が 1 回の作業 (半日〜1日) で完了できる単位'),
 ('type/要判断', 'fbca04', 'オーナー (@hapx2yuki) の決定が必要。決定内容をコメントに残す'),
 ('type/不具合', 'd73a4a', '印刷不良・はめあい NG・設計と現物の齟齬・故障'),
 ('area/印刷', '1d76db', 'Bambu X2D での 3D プリント (プレート単位)'),
 ('area/組立', '0052cc', '骨格・サブアセンブリの組立'),
 ('area/配線', '006b75', 'ハーネス製作・本体配線'),
 ('area/電装', '0e8a16', '電源・基板・LED・サウンドの電気系'),
 ('area/ファーム', '5319e7', 'ESP32 / XIAO のビルド・書き込み・Web UI'),
 ('area/試験', 'e99695', 'ベンチ試験・歩行試験・計測'),
 ('area/仕上げ', 'c2e0c6', '意匠シェルの接着・塗装・装飾'),
 ('area/CAD', 'bfd4f2', 'config.py 更新・STL 再生成・検証スクリプト'),
 ('area/測定', 'fef2c0', 'ノギス実測・電流・重量などの実測'),
 ('area/ドキュメント', '0075ca', 'docs/ の更新'),
 ('area/運営', 'ededed', 'プロジェクト運営・棚卸し・環境整備'),
 ('res/プリンタ', 'f9d0c4', 'X2D を占有する。印刷キュー (E2) の順番で進める'),
 ('res/本体', 'f9d0c4', '本体 (シャーシ組立品) を占有する。同時作業は調整して'),
 ('並行作業OK', '0e8a16', '手元のパーツ・工具だけで独立して進められる (複数人同時可)'),
 ('prio/P0', 'b60205', 'クリティカルパス。これが止まると全体が止まる'),
 ('prio/P1', 'd93f0b', '次のゲートに必要'),
 ('prio/P2', 'fbca04', '後回し可 (完成度・演出)'),
 ('skill/はんだ', 'c5def5', 'はんだ付け・圧着・配線'),
 ('skill/CAD-Python', 'c5def5', 'hardware/src の Python CAD と検証スクリプト'),
 ('skill/ファーム', 'c5def5', 'PlatformIO / Arduino / Web UI'),
 ('skill/模型仕上げ', 'c5def5', '接着・ヤスリ・塗装・現物合わせ'),
 ('skill/プリンタ操作', 'c5def5', 'Bambu Studio / AMS / フィラメント運用')]


def R(current, next_step, completion, purchase, printing, evidence, progress='現物・実行証拠待ち'):
    return dict(current=current, next_step=next_step, completion=completion,
                purchase=purchase.split(), printing=printing.split(), evidence=evidence,
                progress=progress)


REVIEW = {
'E1': R('2026-09-05にAmazon履歴から脚14・MG90S11・ES9251II3などを照合した。現物型番・寸法・印刷使用版の実測表は未提出で、注文/配達を準備完了の根拠にしない。','P-01/P-02で現物を一覧化し、P-03/P-06/P-07の各実測を並行して進める。P-04は実測反映と影響整理、P-05は部品ごとの再使用判断を行う。','子課題の実測・版照合・再使用判断が揃い、未解決設計を隠さず下流条件へ渡した記録。','ap-001 ap-002 ap-003 ap-004','plates leg-frame','README.md','棚卸し・実測待ち'),
'E2': R('既存3MF27個中9個は現行STLと不一致。未変更の意匠にも嵌合未解決品があり、旧プレート順の一括印刷はできない。','追加印刷一覧の部品行で欠品・版・条件を照合する。プリンタ1台を予約し、必要な標準1個の試験から残数へ進む。PR-04→L-02→PR-11を優先し、設計待ちを他部品へ広げない。','必要部品ごとの印刷/再使用/不要を記録し、使用STLと3MFのSHA・材質・設定・個数・写真を保存。','ap-003','plates leg-frame arm head-camera-audio cabin-decor candidates','manufacturing.md','個別印刷条件の整理済み'),
'E3': R('通常/校正ビルドとホスト故障注入は合格。購入電源の型番・20軸の電流・独立停止の実効性は未測定。','電源単体、PCA疎通、無負荷ファーム、線材準備を並行する。通電は型番の許容電圧と外部停止を確認し、1軸から増やす。','EL各課題の実機ログ、電源収支・配線・独立停止・個体校正表が揃う。','ap-001 ap-002 ap-004 ap-005 ap-007','head-camera-audio cabin-decor','firmware.md','ソフト検証済み・電装実測待ち'),
'E4': R('現サーボの実力と脚印刷強度は未確認。coxa局所干渉は修正したが、足支持と全装備のケース/カバー干渉が残る。','FLの標準1本を組みL-02で段階荷重する。合格後に残り3脚を並行組立し、本体はL-06→L-07→L-08→L-09→L-10の順とする。頭無し仮配置と最終配置を区別する。','片脚保持・頭無し歩行の実測動画と条件が揃う。全装備の不成立を頭無し合格で免除しない。','ap-003 ap-004 ap-007','leg-frame','simulation.md','片脚実機ゲート待ち'),
'E5': R('肩/上腕/前腕の内部逃げと肘殻配置は修正済み。肩ケース対前脚ケース、固定手、腕Guardの左右原型対応が残る。','左右の単体骨格は個別部品の検査後に並行する。本体への吊下げはRV-09/RV-10、固定爪の接着はRV-17、Guardは現物と表示原型の対応確定後に行う。','左右の単体・本体干渉・固定手・外装の証拠を分けて完了。','ap-003','arm','mechanical.md','局所修正済み・組立未確認'),
'E6': R('音声挿入路は修正した。目の固定ケース、カメラ版/FPC、頭内収納、Cabin電装室は未確定。CH_HEADの駆動物は無い。','目・カメラ・裸音声は別ベンチで試す。P-03/P-06/P-07の実測を各保持部へ反映し、頭内はRV-09、電装室はH-06と接合面を共有する。','各単体の実動作・挿入/保持と必要配線が揃い、本体取付条件を明記。','ap-005 ap-007','head-camera-audio cabin-decor','mechanical.md','単体試験・収納設計待ち'),
'E7': R('頭支持、首/Cabin、ガード受け座が未成立。既印刷外装をそのまま接着する段階ではない。','RV-13/14/15/16で支持・公差・挿入経路を確定する。無加工の部品照合と仕上げ見本は並行可能。共通シャーシ/Cabinの編集・本体取付は予約して直列にする。','全装備の支持・配線・取り外し・干渉の実機証拠と、旧品の再使用判断を残す。','ap-006','head-camera-audio cabin-decor candidates','static-assembly.md','機構修正待ち'),
'E8': R('89条件の物理計算は条件付きで、機体の実歩行・会話・撮影を確認していない。','I-08で実購入個体へモデルを更新し、実機は重量/重心→全装備歩行へ進む。会話・カメラの裸ベンチ連携とI-06の記録更新は先行できる。','実機の歩行・会話・撮影・演出と使用条件、完成写真・再現手順が揃う。','ap-004','candidates plates','simulation.md','実機統合待ち'),
'E9': R('開始時515ファイル、生成3工程、23検査、89動的条件を記録。ソフト/検査器の5課題を完了したが、機構・電装の実物条件は残る。','閉じたRV-01/02/03/04/12を維持し、各未解決RVとP-02/P-03の現物照合を進める。最終再生成は共通CAD変更をまとめて直列実施する。','RV-05で未解決設計・実測ゲートの判定を更新し、監査実施と機体完成を区別する。','ap-001 ap-002 ap-003 ap-004 ap-006 ap-007','candidates plates','README.md','監査実施済み・是正継続'),
'P-01': R('2026-09-05のAmazon履歴でHiwonder脚14、MG90S11、ES9251II3を確認。M2.5スタンドオフ320セット、M2/M2.5ねじ430セット(M2.5×6含む)、SPL82×6は配達表示あり。PCA2枚は注文済み・受領未確認。','追加購入一覧を現物ラベル・数量・端子と照合する。M2.5×16のセット内包有無、φ2.2刃/DC電流計/microSDの手持ちを確認する。注文済み品を欠品と推測して重複発注せず、無関係な履歴/注文番号/住所を公開しない。','あり/未着/欠品/仕様違いの表とラベル写真。購入・配達確認を使用可能在庫へ読み替えず、必要な行だけ手配対象にする。','ap-001 ap-002 ap-003 ap-004 ap-005 ap-006 ap-007','plates','manufacturing.md'),
'P-02': R('過去の印刷済み申告は現物未照合。形状変更はSTL10ファイル・12個分、配置のみ2ファイル。現設計139個＋予備2個は追加数ではない。Restは8種9個で肩/上腕が無く、Blue1は標準shin1、Blue2はHeadBottom1、TPUは1個のみ収録。9個の3MF不一致と腕7部品の2壁/15%も検出した。','追加印刷一覧の部品別に元3MF・使用日・材料・壁数・数量を写真付きで照合する。標準/鏡像をラベル付けし、旧品は保存してP-05へ渡す。','部品ごとの再使用/加工検討/再印刷/未確認の表。elbowは形状同一、toeは既存150%を再拡大しないと記録。','ap-003','plates leg-frame arm head-camera-audio cabin-decor','manufacturing.md'),
'P-03': R('Amazon履歴はHiwonder脚14、MG90S11、ES9251II3。設計基準DS3218等との現物一致、180/270度、軸/タブ高さ、6V適合は未確認。購入数量を寸法確認済みと読み替えない。','STD/MG90S/目サーボを型式ごと3個体以上、0.05mmノギスで測る。ケースL/W、ギヤ部込みタブ上/下・厚、穴スパン/ピッチ/径、軸偏心/歯数、中心ビス、ホーンのハブ径/厚/腕穴距離/腕厚、線出口を記録する。型番/許容電圧を通電前に照合する。','config.pyキー対応の実測表とノギス/ラベル写真。駆動脚12/腕6/目2と購入脚14/MG90S11/目3を区別し、残数の健全性もP-04/EL-04へ渡す。','ap-004','leg-frame arm head-camera-audio','mechanical.md'),
'P-04': R('公称値による生成・検査は済んだが、実購入寸法への更新は未実施。全機の既知NGを消すことと実測反映は別作業。','P-03の実測で必要な設定だけ更新し、変更前SHAを保存してSTL→頭加工→URDFを再生成する。全検査結果を保存し新規退行を直す。3MFは別出力へ必要分だけ作る。','実測差分、変更STL一覧、影響する旧印刷品、全検査の結果と残件の対応表。無関係なRVの完了まで実測表の引渡しを止めない。','ap-003','plates leg-frame arm head-camera-audio','manufacturing.md'),
'P-05': R('coxaは穴径だけでなく約5717mm³/個の内部除去、chassisは補強材追加、HeadBottomは材料復元がある。ドリルだけで全て再使用可という旧案は撤回。','P-02/P-04を照合し、各部品の工具経路・残肉・新しい支持面を比較する。elbow2個は取付位置だけ直し、形状変更10ファイルは加工/補強/再印刷を部品別に判断する。','対象と必要個数、再使用根拠、加工図または再印刷版、設計待ち理由を記録。未採用候補を一式の確定部品にしない。','ap-003 ap-006','leg-frame arm head-camera-audio plates','manufacturing.md'),
'P-06': R('マイク挿入路とNeck/Cap座は修正済み。INMP441実装厚、φ20スピーカー厚/端子、接着公差と音響は未測定。','INMP441の外形/厚/音孔/ピン向きとSPK径/厚/端子を測りAUDIO_*と照合する。変更があれば音声部だけ再生成しcheck_audio/check_audio_assembly/check_mouth_chassisへ通す。','実測表、音声部のSHA差分、旧mic受け/Neckの再使用判断をPR-07/H-03へ渡す。','ap-004','head-camera-audio','mechanical.md'),
'P-07': R('基準形状はOV2640、公開資料にはOV3660の102度/85度・EFL1.63mmがある。手元センサーの版とFPCは未同定。','子基板/レンズ/FPCの実物型番と寸法・画角を確認し、XIAO本体/USBも計測する。OV3660候補は原型と混ぜず全視野・取り外し・接続をH-02と確認する。','現品写真・寸法/FOVの根拠・採用カメラ設定・影響するshell/base/carrierの表。基板単体撮影の実施有無を区別。','','head-camera-audio candidates','mechanical.md'),
'P-08': R('96課題とProjectが存在し、監査修正5課題のみClosed。旧72件/全Readyという案内は現状を表さない。','今回の全96本文/依存を同期し、Closed5件と既存担当・コメントを保持する。Ready/Blockedの理由を公開し、協力者の参加権限/自動進捗設定は本人の確認を記録する。','96キーの重複なし照合、依存循環なし、Project URLと参加/権限の確認。招待未実施を完了扱いにしない。','','plates','README.md','運用整備済み・参加確認待ち'),
'PR-01': R('Gray_2にはMouth_Key、TailJoint、Shin_Guard、固定手、腕Guardが混在し、全36個を今すぐ印刷する条件はない。腕Guardは原型左右の対応にも疑義がある。','P-02で不足を確認し、既知交差と無関係な意匠だけ別名プレートへ分離して1個試す。MouthはRV-08、首/CabinはRV-15、ガードはRV-16、手はRV-17、腕GuardはRV-10へ対応を残す。保存3MFの爪/指先は同形複製なので、現モデルの左右鏡像に実物が適合するか確認する。','各オブジェクトの印刷/再使用/保留と理由、150%倍率、灰材割当、SHA・数量・写真。保留品を印刷済みにしない。','','arm cabin-decor plates','manufacturing.md'),
'PR-02': R('Black_1のtoe12個は150%が正。指6個・Cabin Insert・Head Insertにも座/位置未確定があり一括印刷不可。','足はRV-06、指はRV-17、CabinはRV-15、Head InsertはS-08の条件で行を分ける。保存3MFの指は鏡像指定なしの同形複製で、現モデルの左右鏡像へ適合するかもRV-17と確認する。未変更で用途が確定した不足品だけ1個試し、スロット1から実PLA黒へ割当を変更する。','150%と配置を確認した部品別数量/写真、未確定品の保留先、旧150%toeの再使用可否。','','leg-frame arm cabin-decor plates','manufacturing.md'),
'PR-03': R('赤ランプ大4/小4は意匠原型を維持。大の右後側はCabinBackと交差しRV-15で追跡中。手元在庫と赤フィラメント残量、LED透過の実測は未確認。','小4個の不足分はP-02後に単品仮合わせ、大4個の不足分はRV-15で該当座を確認してから試す。各1個で透光・寸法を確認し、PLA赤または白+赤塗装を比較して残数へ進む。実スプール割当を保存する。','必要8個の充足表、使用材/数量/写真とEL-08/S-05へ渡す透光結果。','','cabin-decor plates','manufacturing.md'),
'PR-04': R('FL標準tibia1本が先行対象。旧4本3MFはそのまま送信せず、4壁/40%の公称強度は実印刷強度とは区別する。','P-04/P-05後、現行STLを別名3MFに標準1本だけ配置する。向き・材・壁・充填を記録してL-01へ渡し、残り3本はL-02後のPR-11とする。','標準1本のSHA/設定/写真・実重量と主要嵌合。L-02前に残3本を量産しない。','ap-003','leg-frame plates','manufacturing.md'),
'PR-05': R('足本体4個とthigh_cap4個は同一プレートでも別の設計条件。現TPU支持は不成立でカバーはシャーシ/ガードと交差する。','FLベンチに必要な足本体1個を先に版/ソケット/保持で確認する。残り足はRV-06、thigh_capはRV-14/16の採用案後に不足数を確定する。MouthはPR-07へ分離する。','部品行ごとの1脚試験/残数/保留の記録。足プラグ側を下にした設定と旧版混入防止。全プレート完了をL-01の前提にしない。','','leg-frame leg-shell candidates plates','manufacturing.md'),
'PR-06': R('Restは実際に8種9個を収録し、肩ブラケット左右/上腕左右は入っていない。首・前腕・眼・カメラ・音声受けが混在し、前腕は現STLと不一致。旧名称から全腕部品が揃うと判断しない。','部品別にP-03/P-06/P-07の実測と対応RVの条件を確認し、必要な単体だけ別プレートで1個試す。肩/上腕の不足分は現STLから追加する。pod_neckとeye/cameraは未採用候補を本流へ混ぜない。','肩/上腕/前腕/爪座/眼受け/カメラ受け/音声受け/首の引渡し台帳。各組立課題は自分の部品行の合格を確認する。','ap-003','arm head-camera-audio cabin-decor candidates plates','manufacturing.md'),
'PR-07': R('Cannonの挿入路、NeckのBall/Cap座は本流修正済み。Mouth_Neckは現存Blue_2に無く、印刷済みか履歴確認が必要。','P-06実測とRV-08のキー公差条件を反映し、Cannon/Ball/Neckとmic/spk受けの必要分だけ1組作る。mic受けは必要なら0.12mm層で試し、砲口からの挿入を確認する。','対象版/数量/設定/写真、旧Neck/Cannonの内部加工可否、H-03へ渡す一式。','','head-camera-audio plates','manufacturing.md'),
'PR-08': R('v2ホロー版でもHeadTopと設計基準ケースは597〜1277mm³交差し、既存7タブの頭支持も未成立。現Blue1にはHeadTopが無く標準shin1だけなので、プレート名やv2所持だけでは完了できない。','P-02で既印刷版を保存し、RV-09の収納とRV-13の支持が決まってから採用STLを確認する。再印刷/既品加工は頭の開閉・目/カメラ/配線を含めて比較する。','採用版と旧品の差、必要加工/印刷数、頭内隙間・支持・開閉確認。寸法未確定の頭を追加印刷しない。','ap-006','head-camera-audio candidates plates','mechanical.md'),
'PR-09': R('骨格の再印刷は全数指示ではなくP-05の部品別判断。chassis追加カラーとcoxa内部変更を穴拡張だけで代替できない。','P-05で確定した変更対象だけ別名3MFで作る。試験品→合格後の不足残数とし、変更していないfemurや配置だけ変わったelbowを自動再印刷しない。','対象・必要数・旧品再使用の理由とSHA/設定/写真。不要ならP-05の根拠付きで不要完了を記録する。','ap-003 ap-006','leg-frame arm head-camera-audio plates','manufacturing.md'),
'PR-10': R('カメラbaseの旧ポケット差だけでなく、OV2640/OV3660と主基板/FPC保持の選択が未確定。shellを無条件に再使用可とはしない。','P-07の同定後H-02の採用構成に合うbase/shell/carrierを比較する。旧White_3を即送信せず必要な1組だけ別名保存し、FPCを通した仮組みを優先する。','カメラ版、採用STL、既品再使用/変更、1組の写真と挿入/FOV確認。','','head-camera-audio candidates plates','mechanical.md'),
'PR-11': R('残りtibiaはRR標準1、FR/RL鏡像2。FL試験の合格前に3本を追加する根拠はない。','L-02が同じ版/材/設定で合格した後、不足をP-02で照合して必要分だけ印刷する。材や姿勢を変えた場合は強度と嵌合を再確認する。','標準1/鏡像2の充足、4壁/40%と向き、SHA/写真、L-03/04/05への引渡し。','','leg-frame plates','manufacturing.md'),
'EL-01': R('購入履歴でHENGE UBEC(B07JJCW9W2、5/6V・瞬間12A表記)を確認した。連続定格・現物ラベル・設計の10A基準との差、無負荷出力と2S末期の入力余裕は未測定。','型番と許容入力をP-01で照合し、サーボ未接続で6.0V/5.0Vを測る。2S→ヒューズ→DC定格SW→二系統、VBAT分圧100k/33k、サーボ電源外部バスを確認する。','無負荷の電圧、型番/ジャンパ/配線写真と外部遮断試験。電流/発熱/低入力はEL-09へ別記録。','ap-004 ap-007','cabin-decor','firmware.md'),
'EL-02': R('PCA2枚セットは注文済みで配達日表示が無く受領未確認。ACK検査はソフト修正済み。現ボードのアドレス/プルアップ/ヘッダ向きと独立OEは実物未確認。ch12の駆動先は無い。','board0=0x40(脚12)、board1=0x41(腕6/目2)を設定し、ロジック3.3VとSDA/SCLを測る。サーボV+は外部バスへ分岐、信号/GNDを共通化。最終固定はH-06の電装室に合わせる。','0x40/0x41疎通ログ、表裏写真、プルアップ電圧、OE配線の実測。旧頭中央スタック寸法だけで取付を確定しない。','ap-001 ap-002 ap-007','cabin-decor','firmware.md'),
'EL-03': R('CALIBRATION_MODEのホスト試験とビルドは合格したが、実ESP32への書込・AP接続・PCA出力は未確認。','機体と対象ボードを同定して既存設定/ファームを保全後、校正版をベンチへ書込む。APの実資格情報はローカルだけに置き、USBと外部5Vを同時投入しない。','書込対象/版・ビルド・起動/I2Cログ、AP画面。サーボ未接続で校正版の中立と低電圧/脱力経路を確認する。','ap-007','','firmware.md'),
'EL-04': R('実サーボの中立/方向/可動端は未校正。通常機体は脚12+腕6+目2の20軸で、CH_HEAD予備は通電対象外。','P-03の許容電圧確認後、リンクを外した1個ずつ1500µsへ合わせる。小刻みなパルスで角度/電流を測り個体番号と軸位相を記録し、500/2500µsへ直接飛ばさない。','購入脚14/MG90S11/目3の個体表と駆動脚12/腕6/目2への割当・写真・パルス角度表。270度品などは軸別校正とし全軸共通DEG_RANGE変更で混在を隠さない。','ap-004 ap-007','leg-frame arm head-camera-audio','firmware.md'),
'EL-05': R('脚ハーネス12本の実長・端子/線種・導通は未確認。後の軸配置変更があるため最終束ねと長さ確定は本体側で行う。','AWG16幹線と各枝線/信号を用途別に準備し、電源をPCAへ流さない構成で仮長12本を作る。新しい軸とφ9通路で全可動域の張り/擦れをL-08で確認する。','12本の線種/仮長/端子極性/導通表と写真。最終切断/束ねは配置確定後と記録。','','leg-frame','firmware.md'),
'EL-06': R('腕6/目2の電源は外部バスを使う設計。6V適合・実電流と頭内通路は未測定。','型番別電圧を確認して8本を余裕長で製作し、電源と信号を区別する。肩/目の最終配置が決まるまで軸根元を固定せず、実可動域で張りを確認する。','8本の線種/長さ/導通/極性と実取り回し写真。電源電流とPCA基板定格を推測で代用しない。','ap-004','arm head-camera-audio','firmware.md'),
'EL-07': R('通常ビルドは初期脱力→Web「立つ」で20軸を順次通電し、I2C/VBAT故障は停止ラッチする。実ボード動作は未確認。','CAD全体の確定を待たずサーボ未接続で通常版/AP/UI/故障経路をベンチ確認する。次に校正済み1軸で符号/出力を確かめる。本体荷重試験はL-09の支持台条件へ分離する。','対象ボード/版のビルド・書込・UIログ、再読込で再通電しない確認、JOINT_SIGN/ARM_SIGN/チャンネル表。','ap-004 ap-007','','firmware.md'),
'EL-08': R('DFPlayerと74AHCT125は購入履歴に配達表示あり。WS2812×12とmicroSDは履歴検索で未確認。LED12/DFPlayerのホスト検証は済んだが、実点灯/再生・5V電流は未測定。','74AHCT125を3.3→5V変換に使い、OE/未使用入力を確定してLEDを1灯→12灯で試す。DFPlayerは1kΩ直列とFAT32 SDで再生し、LED0/1..3/4..11の順を記録する。','12灯動画、DFPlayer再生、5V電圧/電流と使用音源/配線。接続基板を頭内に無理に詰めずH-06へ寸法を渡す。','ap-004 ap-005','cabin-decor head-camera-audio','firmware.md'),
'EL-09': R('電源収支はUNVERIFIED。旧9〜14Aは仮定であり、正機械仕事率から保持電流/銅損は求められない。','EL-01やL-02/L-10の成功/失敗ログから6Vバス、5Vバス、電池入力の電流/電圧/温度を別計測する。入力電力換算とUBEC型番別の連続/瞬間定格、SW/ヒューズ/線材を照合する。','実型番・負荷/時間・最低入力・ピーク/平均・温度の表と継続/交換の根拠。歩行合格待ちで対策検討を止めず、10A直列テスターを全機へ挿入しない。','ap-004 ap-007','cabin-decor','README.md'),
'EL-10': R('手動脱力と異常停止は実装済み。自動休止スタンス/支持付き復帰と10分保持温度の比較は未実施。','脚の負担が下がる休止姿勢と停止/再開経路をモデルで比較し、足裏/干渉を確認する。実機は支持を確保して現行版と温度を比較し、自動脱力で倒れる条件を除く。','トルク低減量、遷移/再開の検証、10分の実温度・電流比較。未測定の保持割合を定格余裕と扱わない。','ap-004 ap-007','leg-frame candidates','simulation.md'),
'L-01': R('FL標準骨格は片脚試験用。coxaポケット改訂と実サーボ寸法の照合が必要で、全装飾の接着を先行しない。','PR-04標準tibia1本、P-05で認めたcoxa/femur、校正済みサーボを使う。ケースタブ/ホーン共締め/中心ビスを確認し、足本体1個のソケットと保持を別検品して組む。','標準FLの版・個体番号・側面/ホーン写真、低速の干渉/ガタ/緩み確認。PR-05のthigh_cap全数待ちは不要、試験用足の充足記録は必須。','ap-003 ap-004','leg-frame','manufacturing.md'),
'L-02': R('1.2kg×水平155mm=18.6kgf·cmは試験条件であり、6Vの連続定格ではない。実保持・発熱・ホーン滑りは未確認。','現品の6V対応を確認したうえで6V給電し、coxaを固定し無負荷から段階荷重、電圧/電流/角度/温度を記録する。未確認品へ7.4Vを加えない。条件が安定した場合に155mmのレバーで1.2kgを10秒確認し、白化/割れ/滑り/急増時は除荷する。','レバー長・錘・版/個体が分かる動画と値。10秒合格を連続歩行合格にしない。不合格原因はL-11/EL-09へ戻し、L-03/04/05とPR-11を解放しない。','ap-004 ap-007','leg-frame','simulation.md'),
'L-03': R('FRはcoxa/femur/tibiaの鏡像_m。現物版・個体の確認とFLゲート合格は未提出。','L-02/PR-11後、FR用鏡像3点と校正サーボで組む。ホーン共締め・中心ビス・足保持を確認し、装飾は付けず低速で動かす。','FR個体番号/使用版と完成写真、嵌合・ガタ・干渉の記録。RL/RRとは別ベンチで並行可。','ap-003','leg-frame','manufacturing.md'),
'L-04': R('RLはcoxa/femur/tibiaの鏡像_m。後脚の最終ポッド側制限は本体取付後に別確認する。','L-02/PR-11後、RLの鏡像3点を組み、ホーン位相と足ソケットを検査する。後脚配線は余裕を残してL-08へ渡す。','RLの個体/版/写真、無負荷の範囲・配線出口・締結検査。前脚の記録を流用しない。','ap-003','leg-frame','manufacturing.md'),
'L-05': R('RRは標準版。残り標準tibia1本の印刷/再使用判断は片脚ゲート後。','L-02/PR-11後、標準coxa/femur/tibiaとRR割当サーボで組む。FLと同型でも各個体のホーン・ケース・ソケットを確認する。','RRの版/個体表、写真と低速検査。FR/RLの鏡像部品を混ぜない。','ap-003','leg-frame','manufacturing.md'),
'L-06': R('最終の頭内電装配置は未成立。頭無しの外部仮置きは可能だが、旧中央PCA/テープ固定を完成配置とは扱えない。','P-05で使えるシャーシと4個の中立ヨーサーボを組み、電源/基板は脱着できる頭無し試験配置にする。battery_cradle、配線穴、重量/固定/短絡防止を確認し、最終室はH-06へ分ける。','仮配置であることを明示した上下写真、4個体/ch表、配線穴の実通し、電池保持。将来のRV-09軸/頭支持変更の影響を記録。','ap-001 ap-002 ap-006 ap-007','leg-frame cabin-decor','mechanical.md'),
'L-07': R('4脚の固定方位はFR15/FL165/RL210/RR330が基準だが、現サーボと実トリムは未確認。','本体を無通電で支持し、中立マークと標準FL/RR・鏡像FR/RLを照合してヨーホーンを共締めする。脚同士の隙間を低速で確認し、未解決の頭/腕は付けない。','4脚上面写真・ホーン締結・個体/ch表と実接地。中立0度と115mm保持指令を同じ姿勢と呼ばない。','ap-003','leg-frame','simulation.md'),
'L-08': R('12chの配線経路は設計上の案で、実コネクタ径と全可動域の余長は未確認。','L-07の脚にEL-05のハーネスを仮配線し、電源は外部バス、PCAは信号/GNDへ分ける。FR0/1/2、FL3/4/5、RL6/7/8、RR9/10/11を1本ずつ照合する。','個体/ch/極性表と全域で張り/擦れ/噛み込みが無い写真。穴が詰まる場合は負荷経路を確認してから再設計する。','','leg-frame','firmware.md'),
'L-09': R('通常版は初期脱力。床上の中立から順次起動する計算は0.454秒で転倒し、実機の起動手順は未確認。','支持台で支え、全サーボ外し電圧確認→1個→脚12の段階確認を行う。Web「立つ」で起動後に脚の符号/位相を確認し、立位で支持を下ろす。腕6/目2は単体/後工程で確認し、この頭無し工程のため取付を前倒ししない。','各段階の電圧/電流、採用Trim/JOINT_SIGN/ARM_SIGN、立位動画。未使用ch12は未接続、USBと外部5Vは排他。','ap-004 ap-007','leg-frame','firmware.md'),
'L-10': R('頭無し実機の立位/歩行は未確認。条件付きの全装備モデルや旧動画を実機合格に置き換えない。','L-09後に平坦面・115mm/歩幅50%から前進/旋回/停止を試し、電圧/電流/温度を記録する。装飾なしでも硬足が先行するため試験用接触面を記録し、滑りがあれば支持を直す。','転倒/脱調なしの動画と試験用の質量/足接触/仮電装条件。失敗はEL-09/L-11へ戻し、フルドレスへの合格外挿をしない。','ap-004 ap-007','leg-frame candidates','simulation.md'),
'L-11': R('DS3218の6V補間19.94kgf·cmは公称ストールの仮定。購入型番と継続保持能力は未確定。','P-03とL-02の成功/失敗ログを使い、6V運用の歩幅/スタンス/軽量化を先に比較する。力不足を再現した軸だけ、6V適合のケース・連続能力・費用で交換候補を検討する。','同じ荷重/形状/温度/時間での比較と採用理由。サーボ全14個交換や未同定品への7.4V化を既定にしない。','ap-004','leg-frame candidates','simulation.md'),
'A-01': R('右腕の内部干渉は局所修正済み。固定爪の座/公差が未確定で、肩対前脚の本体干渉は単体腕とは別問題。','実測適合した標準shoulder/upper/forearm/claw_mountを部品別に受取り、校正済みMG90Sで組む。肩pitch 0度は水平、校正範囲の基準pitch -45〜85度・肘0〜95度・肘中立45度を照合する。固定爪接着はRV-17の成立後に行う。','右腕単体の版・P-02/P-05の該当品受入れ・2個体番号・肘0〜95度/ピッチ域の無負荷動画と固定爪保持。PR-06/Gray/Black全プレートの完了待ちは不要。','ap-003','arm plates','mechanical.md'),
'A-02': R('左腕は_L骨格を使用。先行claw_mount_Lは旧3MFに腕7部品を含むため、1個だけ印刷済みと決めつけない。','P-02で_Lの実在庫/壁数を照合し、実測適合部品を受取る。左もpitch -45〜85度・肘0〜95度・肘中立45度を校正範囲の基準として確認する。爪ハブはArm_Left_Claw_GreyでRV-17の公差確定後に固定する。','左腕単体の版・P-02/P-05の該当品受入れ・個体・設定と動作/保持写真。右腕との鏡像・ヨー符号を記録し、右の合格を代用しない。','ap-003','arm plates','mechanical.md'),
'A-03': R('停止でも肩pitchケース対前脚pitchケースが約451/413mm³交差する。腕単体の合格だけでは本体へ吊れない。','RV-09/RV-10の軸/ケース配置を確定しL-07の脚と無通電で仮組みする。右16/17/18、左20/21/22と位相を照合し、TUCK/READY/REACH/WAVEを低速で試す。','全プリセット・脚停止/遷移の隙間、配線余長、個体/ch/符号と動画。連成ガードはtargetと出力後角で確認する。','ap-004 ap-007','arm leg-frame','simulation.md'),
'A-04': R('肘殻2個は形状同一で局所Y=-13.8mmへ配置訂正。腕Guardは現表示がRight原型の標準+鏡像、旧印刷表がLeft/Right各1で対応未確定。','既印刷elbowを保存し新しい座で仮付けする。arm_pod/GuardはRV-10で原型・左右・取付を確定後、内側支持と脱着を確認して固定する。','原型名/左右/版の表、肘端と4プリセットの外装写真・隙間・接着保持。Guardを未確認で追加印刷しない。','','arm plates','mechanical.md'),
'H-01': R('目ポッドの固定ケース/保持板は頭内の脚yawケースと交差する。目単体の中立/保持/6V適合は現物未確認。','校正済み目2個と実測適合carrierを受取り、ホーン共締め2本/目(全4本)で先にポッドへ固定し中立位相を合わせる。現構造では中心ビスに工具が届かないため、軸との保持/着脱は実物で確認する。単体でkyoro/front/scanを確認し、頭へ接着するロールはRV-09の配置後に確定する。','左右24/26chの個体/パルス/ドット位相・P-02/P-05の該当品受入れ・保持/動作動画。瞬着でスプラインへ不可逆固定する前に着脱と位相を確認。','','head-camera-audio plates','mechanical.md'),
'H-02': R('OV3660用のレンズ座/FPC/主基板トレー候補を作ったが未採用。現カメラ保持板はHeadTopとも約0.542mm³交差する。','P-07の現品同定後にbase/shell/carrierと主基板/USB/FPCを仮組みする。OV3660で既存瞳10mmを保つ候補は後退≤4.05mmを基準とし、旧6.57mmを流用しない。実品の画角/FPCで再計算し、実接続/撮影・全視野・取り外し・熱・保持を試す。','採用カメラ版/寸法/画角/経路と撮影画像、消費電流、頭内配置。基板を空き場所へテープ留めしただけで成立としない。','','head-camera-audio candidates','mechanical.md'),
'H-03': R('砲身の挿入ボア/キー溝とNeck/Cap座は修正済み。実マイク/スピーカーの圧入、8芯通線、音孔位置は未確認。','P-06/PR-07で認めた部品を仮組みし、micのL/R=GNDと音孔、SPKの向きを確認する。6+2芯をCannon→Neck→Ballへ通し、着脱できる状態で導通を測る。','挿入前後/音孔/キー/通線の写真、部品版・8芯導通と保持。spkワッシャ1個はPR-06の首/眼完了を待たず部品別に受取る。','','head-camera-audio','mechanical.md'),
'H-04': R('I2S形式/部分書込/取消は修正しホスト試験合格。実音響と手元MAX98357AのSD回路、1W SPKの出力上限は未確認。','砲身組込を待たず裸配線でINMP441とMAX98357Aを低音量から試す。GPIO26/25のクロック共有、27出力/33入力と基板別SDを確認し、mock自己検査→PTT→440Hz再生へ進む。','実録音/再生、基板/配線/音量制限、5V電流とクリップ/過熱の記録。裸試験合格後の筐体内音響はH-03/S-04で再確認。','ap-004','','firmware.md'),
'H-05': R('Ball/Neck/Capの大きい干渉は内部座で修正済み。Mouth_KeyはCannon約0.275/Cap約0.070mm³の公差未確認が残る。','RV-08で認めた一式とCap/Key/Pegを部品別に照合し、8芯を残した仮組みで挿入/保持を確かめる。旧standoff値だけを頼りに押込み接着しない。','使用版と全挿入/保持、音声配線、前方/側面写真。小キーを無理に押して白化させず加工公差を記録。','','head-camera-audio plates','mechanical.md'),
'H-06': R('Cabin電装室/棚/着脱Peg候補は局所71項目合格。基板実寸・首/Eye/Ballとの全体干渉・通線/強度は未確定。','購入基板・USB/電源端子を実測し、RV-15と境界寸法を共有して部品配置/棚/保守経路を修正する。ESP32/PCA/電源を収め、短FPCのXIAOはH-02の頭内保持へ残す。','全体干渉・基板挿入/脱着・保持/熱/通線の検査と候補採否。変更質量/重心をI-08、印刷影響をP-05へ渡す。','ap-001 ap-002 ap-006 ap-007','cabin-decor candidates','cabin.md','候補比較済み・全体未成立'),
'H-07': R('CH_HEAD/ch12の実駆動物は無く、修正版は常時停止。20軸起動から除外し、SG90等は予備扱い。','PCA ch12を未接続で維持し、実ボードで出力停止と配線ラベルを確認する。新しい可動部を追加する場合だけ別設計/部品判断へ切り分ける。','予備維持の決定、ch12未接続写真と出力停止確認。新サーボ購入/架空9g質量を復活させない。','','head-camera-audio','firmware.md','停止実装済み・予備端子確認待ち'),
'S-01': R('首梁とTailJointBlue約3282/Ball約2048mm³が交差する。先端だけにスリーブを被せる旧手順は全長では成立しない。','RV-15/RV-07の採用形状・通線・強度が決まった後、部品を別受取りし全長の挿入と締結/配線/保守を無通電で確認する。','採用版/締結長/全長写真、支持荷重と取り外し記録。PR-06全体待ちの代わりに首部品の個別合格を確認する。','ap-006','cabin-decor candidates','neck-reinforcement.md'),
'S-02a': R('FL標準脚のthigh_cap/ガード/足支持が未成立。ガードは殻の固体内へ埋まる旧配置のまま接着できない。','L-10後、RV-06/14/16の足支持・カバー・挿入座をFL標準で照合する。shin_shell標準、M3×40とナット、150%toe3個の版/方向を仮組みする。','FLの外内写真・全域隙間・ガード保持・支持荷重。TPUが支えることを実接触で示し、単一凸包の動画を代用しない。','','leg-frame leg-shell candidates plates','static-assembly.md'),
'S-02b': R('FRは鏡像shin_shell_m。前脚の硬toeはTPUより18.102mm先行し、装飾取付には足支持修正が必要。','RV-06/14/16の採用座と支持をFR鏡像で確認する。標準部品と混ぜずshin取付、ガードの全挿入、toe3個の150%と根元座を順に仮組みする。','FRの版/方向/外内写真、全域で腕/隣脚と干渉せず支持荷重が想定面に乗る記録。','','leg-frame leg-shell candidates plates','static-assembly.md'),
'S-02c': R('RLは鏡像shin_shell_m。後脚は硬toeがTPUより22.034mm先行し、ポッド側の可動域も要確認。','採用済みの足/ガード/カバーをRL鏡像に照合し、150%toe3個とM3貫通締結を仮組みする。ポッド側クランプと停止/旋回で首/Cabinへの隙間を測る。','RLの接触/全域隙間/締結/挿入写真。FRの鏡像部品と同形でも後方配置の結果を別記録にする。','','leg-frame leg-shell candidates plates','static-assembly.md'),
'S-02d': R('RRは標準shin_shell。標準FLと同じ部品でも後脚の支持/首干渉条件は異なる。','RV-06/14/16後にRR標準でガードの挿入・150%toe・足支持を仮組みし、停止から後脚旋回まで検査する。','RRの使用版、外内写真、ポッド側隙間・足反力・固定方法。4脚全体の共面性確認へ値を渡す。','','leg-frame leg-shell candidates plates','static-assembly.md'),
'S-03': R('HeadTopケース収納・7穴支持が未成立。Head_Plate/Head_Bottom_Capは不採用。旧頭中央PCAとcarrier現物合わせ接着を既定にしない。','RV-09/RV-13とH-01/H-02/H-06の採用配置で頭上下を仮組みする。目/カメラ/FPC/配線・開閉・固定受けを確認し、S-08で位置・受け座・挿入が成立した装飾だけ固定する。','合わせ目・支持/締結長・全ヨー隙間・眼動画/カメラ画像・取り外し手順。確認済み頭装飾の個別引渡しで進める。','ap-006','head-camera-audio cabin-decor candidates','mechanical.md'),
'S-04': R('口とシャーシの挿入363姿勢は合格したが、実通線・接着/保持・装着後音響は未確認。','H-05の一式をS-03へ仮取付し、8芯が受け穴を通ることと採用した-18度基準姿勢を確認する。Ball保持と腕の全プリセット隙間を測り、PTT/再生を再試験する。','正面/側面/配線写真、保持方法、腕隙間と筐体内音声動画。スナップ成立を公称径だけで決めない。','','head-camera-audio','mechanical.md'),
'S-05': R('CabinBackは6.3075mm下げてPegを整合した。電装室/首/Eyeの干渉が残り、Front/Backの最終接着はできない。','H-06/RV-15で採用した内部と接合部を使い、欠品意匠/LEDを個別に受け取る。非対称特徴で向きを確認し、基板・通線・保守を試してから外装を固定する。','向きの根拠、Peg/目/装飾の座、開閉と電装収納、LED写真。所在不明の元Downloads3MFを再確認済みとは記さない。','ap-005','cabin-decor candidates plates','cabin.md'),
'S-06': R('首/Cabinの通線と全長装飾、印刷強度が未成立。旧「フランジ穴を現物合わせで開けて完成」は根拠不足。','S-01/S-05の採用部を無通電で合わせ、支持フランジ/当て板/ねじ長と通線経路を検査する。電装を取り外せる順序を保ち、仮支持で段階荷重する。','取付高さ/後脚隙間/荷重とたわみ・配線/保守写真。対角2脚だけで不安定に持ち上げず、支持台や秤で重心確認へ引継ぐ。','ap-006','cabin-decor candidates','neck-reinforcement.md'),
'S-07': R('LED/DFPlayerの最終位置と5V余裕は未測定。頭内の空きへ追加基板を置く旧案は採用できない。','EL-08の検証済み配線をH-06の電装室へ収め、LED0〜11を実番号で照合する。5V全負荷、熱、音声との同時動作、首通線と保守開閉を確認する。','全灯/再生動画、各番号/配線表、5V電流/電圧/温度。I-01の完成重量へ基板と線材を含める。','ap-004 ap-005','cabin-decor head-camera-audio','firmware.md'),
'S-08': R('Head_Insert4個のうち2個の位置が未確定。既存の実測ラベル付きInsert1もHeadTopと128.245mm³、推定Insert2は32.822mm³、推定Screw2は8.723mm³交差する。Screw1も腕ヨーケースと5.400mm³交差しRV-09で追跡中。','所有する実物写真/元3MFの取得可能性を確認し、位置だけでなく全Insert/Screwの受け座・挿入・ケース隙間を原型で検査する。実測座標ラベルを嵌合合格とせず、成立した採用形状だけJSON/表示/URDFへ反映する。','正面/側面/上面の一次写真、採用座標/数量、全受け座と挿入/保持の根拠、または不採用の明示判断。S-03へ確認済み品だけ渡し機体のベンチ試験は止めない。','','head-camera-audio cabin-decor','static-assembly.md'),
'I-01': R('現行URDF推定質量は2.726350kg。旧2.78/3.0kgは実測重量ではなく、採用予定電装室/支持候補で今後変わる。','Mouth/LED/配線を含む全装備の実重量を測り、支持台と複数秤で前後左右の荷重を記録する。CG_XY/TOTAL_KGを実測へ更新し、移動する電池位置を保持/配線制約内で比較する。','電池込み総重量/内訳・秤配置/支持荷重・重心の計算と設定差分。I-08/L-11へ同じ入力を渡す。','ap-004','cabin-decor candidates','simulation.md'),
'I-02': R('フルドレス実歩行は未実施。現足のTPU反力0%、自己干渉ありのため条件付きモデルだけで合格にできない。','I-01/RV-06/RV-07と設計の干渉修正後、支持台から115mm/歩幅50%で開始する。前後/横/旋回/停止再開を段階的に試し、20軸Trimと電源/温度/電池を記録する。','実動画・採用形状/サーボ/足材/床・連続時間・電圧/電流/温度・姿勢の記録。転倒や飽和を別件として残す。','ap-004 ap-007','leg-frame candidates','simulation.md'),
'I-03': R('voice_bridgeのmock/ホスト通信は検証済み。実マイク往復・テザリング・外部API/音声の利用結果は未確認。','H-04の裸ベンチで2.4GHz STA/mDNSまたは実IPを確認し、ローカル環境変数でAPIを設定してPTT会話する。API/音声権利と公開範囲を選び、秘密値をIssueへ貼らない。','PTT→応答の動画、往復遅延/切断復帰・使用設定の非秘密情報。Mouth装着待ちでネットワーク検証を止めず、装着後はS-04で再確認。','','head-camera-audio','firmware.md'),
'I-04': R('カメラ連携のHTTP境界はホスト検証したが、実XIAOの撮影と会話応答は未確認。','H-02のカメラを同じネットワークへ接続し、capture URLと形式を確認する。voice_bridgeのcamera-urlで既知対象を撮り、画像内容と応答を比較する。','使用カメラ版/FOV・取得画像と対応会話・遅延/タイムアウトの記録。連続映像を静止画として無期限受信しない。','','head-camera-audio candidates','firmware.md'),
'I-05': R('目/LED/DFPlayer/腕の同時演出は実機未確認。旧「腕退避が半分未満なら正常」という割合は普遍的判定ではない。','全装備歩行条件で目モード/方向バイアス、LED番号、起動/歩行音、腕WAVEを順に確認する。脚のtarget/実出力角に応じた退避を記録し干渉/電源余裕を見る。','演出と歩行が同時に分かる動画、20軸/ch12未使用、電圧/電流と異常の有無。固定割合で保護の成否を判定しない。','ap-004 ap-005','arm head-camera-audio cabin-decor','firmware.md'),
'I-06': R('監査・配線・製作影響の文書は更新済み。現物の採寸・加工・組立で新たに得た知見はまだ無い。','課題ごとに実測値/使用版/写真が出た時点でassembly/wiring/print_manifest/HANDOFFへ反映する。今回の購入・印刷一覧と全96課題のリンクを保守する。','Refs付き変更記録、実測日/出典/未検証の区別、製作手順のリンク確認。監査文書の更新だけで将来の実物知見を完了扱いにしない。','','plates','README.md','監査文書反映済み・製作知見待ち'),
'I-07': R('公開済みの動画は物理計算の条件付き例。完成実機の写真・歩行/会話/カメラ映像は未取得。','実機のI-02/I-03/I-04/I-05結果が揃ってから正面/側面/上面と機能動画を撮る。READMEへ使用条件と協力者を記録し、途中の計算映像は表示を分ける。','完成実機の媒体とREADME変更、全機能の実行根拠。計算結果を実機完成の紹介に使わない。','','plates','README.md'),
'I-08': R('89条件・18姿勢・16回帰と入力一致は実施済み。基本71は58合格/2不合格/3転倒/8初期接触不成立。設計基準ケースと購入個体の一致は未確認。','P-03等の実測と採用CADを取り込み、STL→URDF→全条件を同じ入力で再実行する。自己干渉/材料別反力・20軸出力・速度トルク・刻み感度を保持し、実機の摩擦/電流/温度へ照合する。','実購入版での入力SHA、全条件/失敗・警告、実積分qpos動画と実測照合。平地58合格を頭収納/足支持/強度の合格へ拡張しない。','ap-004','candidates leg-frame head-camera-audio','simulation.md','設計基準の検証済み・実測反映待ち'),
'RV-01': R('操作画面、低電圧/0V、I2C書込、腕脚ガード、ch12除外、I2S/通信取消を修正。通常/校正ビルドと実コード故障注入は完了し#81はClosed。','完了を維持する。実書込/符号/中立はEL-03/EL-07/L-09、実音響はH-04、CPU/I2C断時の独立停止はRV-11へ引継ぐ。','保存済み修正前再現・ホスト/ビルド・1563フレーム照合の固定記録。新しい実機完了をこのCloseへ混ぜない。','ap-007','','firmware.md','完了（ソフト修正・検証）'),
'RV-02': R('27個の3MF比較と生成コード修正を完了し#82はClosed。9個不一致、形状変更10/配置変更2、原型/旧媒体の保持を記録した。','完了を維持し、現物版の照合をP-02、加工/再印刷をP-05へ渡す。新しい腕Guardの原型対応はRV-10/PR-01で追跡し旧監査完了範囲を広げない。','保存された比較/負例/保持SHAと個別引継ぎ。旧3MFを一括上書きせず、実印刷なしと明示。','ap-003','plates arm','manufacturing.md','完了（3MF検査・生成修正）'),
'RV-03': R('NG/例外を非0終了へ修正して#83はClosed。53回帰は合格し、最終8NG/1未検証を失敗として保存した。','完了を維持し、新しい検査を追加する時は空/NaN/例外/保存失敗の負例を既存回帰へ追加する。現行部品NGは対応RVで修正する。','負例と正常経路の回帰ログ、非0判定を維持した最終検査記録。NGを消すための閾値緩和をしない。','','plates','integration-peer-review.md','完了（検査器の失敗検出）'),
'RV-04': R('既存Status/担当/コメント保持、冪等同期、対象限定と依存検査を修正して#84はClosed。監査時96課題173依存の照合を保存した。','完了を維持する。今回の96本文/新依存はdry-run→同期→全件照合し、既存Closed5件と担当/コメントを保持する。進捗変更は今回の明示範囲だけに限定する。','同期回帰と本文/関係/状態の全件比較、再実行差分0。保存された旧173依存の履歴を最新値へ書換えない。','','plates','README.md','完了（同期処理修正）'),
'RV-05': R('生成3工程・23検査・89物理条件を記録したが、23検査は14合格/8NG/1未検証。全体合格のゲートは未達。','RV-06/07を含む各機構/電装の採用案と実測が出揃った版で、生成→全検査→物理計算を再実行する。購入/印刷の影響と下流実機条件を全課題へ反映する。','同一版の全検査表と未解決なしの設計判定、必要な実測ゲートの合格根拠。未解決の設計/実測が残る間はOPENを維持し、次の是正を記録しただけではCloseしない。','ap-004 ap-006 ap-007','candidates plates','README.md','監査実施済み・全体判定未達'),
'RV-06': R('150%toeではTPUより前18.102/後22.034mm先行、材料別計算のTPU荷重0%。未採用の1.5mm靴候補4条件はTPU支持99.79〜99.92%。','取付角/隠し座/着脱支持を比較し、採用候補1脚で摩擦・圧縮・保持・外観を確認する。全到達姿勢の支持と接触を再計算し、現物トゥ根元座も照合する。','足裏先行/反力/たわみ/接着の実測、外観比較と採否、同じ形状の全回帰。toe無しベンチ合格を全装備支持へ流用しない。','','leg-frame leg-shell candidates','simulation.md','候補比較済み・実支持未成立'),
'RV-07': R('中実断面の合格は4壁/40%印刷を保証しない。首の近似安全率2.71は要求3未満で、腕2壁/15%の過去3MFもある。','P-02の使用材/向き/壁/充填を確認し、同条件試験片または既印刷品を仮支持で段階荷重する。RV-15の首通線/補強案とケース/ねじ/層方向を連携評価する。','荷重/たわみ/残留変形/層割れ/締結の実測と採用条件。サーボ保持のL-02と材料強度を別記録にする。','ap-004','leg-frame arm cabin-decor candidates','mechanical.md','感度検証済み・印刷強度未確認'),
'RV-08': R('マイク挿入/Neck球面座/Cap座/シャーシ逃げと支持カラーは修正し挿入363姿勢を検査。Mouth_Keyの微小重なりと実保持公差は残る。','Cannon/Cap対Keyの深さと現印刷公差を測り、見えない座を最小修正する。P-06の実部品を入れた全挿入/通線を確認し、前タブ+3mmの締結条件をRV-13へ渡す。','小キーの公差/保持を含む全体組立検査、単一閉体/残肉と旧品加工可否。実音響はH-04へ分離し局所修正だけでCloseしない。','ap-006','head-camera-audio plates','mechanical.md','主要干渉修正済み・キー公差待ち'),
'RV-09': R('旧検査のケース上方11mmは誤りで、タブ下ケース約28mmが上へ入る。HeadTopと各基準ケース597〜1277mm³、梁89.23mm³等が交差し有限探索は未成立。','P-03/P-07の実購入寸法を採用前に照合し、既存脚リンク/外観を保つ軸/高さ/向きと目・カメラの同時配置を比較する。ケースを殻の凸包外に出す案は内部削りで成立扱いにしない。','全ケース/眼/基板/梁の同時成立、壁厚/挿入/工具/配線の根拠と採否。固定軸をRV-13/14/10へ渡し有限失敗を不可能の証明と呼ばない。','','head-camera-audio candidates','simulation.md','有限探索済み・収納未成立'),
'RV-10': R('腕1664姿勢とcoxa約199万組の局所修正は合格。肩pitch対前脚pitch約451/413mm³は残る。腕Guardは表示Right×2(鏡像)と旧Left/Right各1が不一致。','RV-09と軸境界を合わせ肩/前脚ケースを同時に成立させる。Guard原型/左右/実印刷と取付位相を独立確認し、必要な表示/CAD/印刷一覧修正を行う。固定手はRV-17、脚カバーはRV-14へ分ける。','本体の全到達姿勢・外装/Guardを含む干渉0、公差/残肉/工具の根拠、旧品への影響。局所合格を全体合格にしない。','ap-003','arm leg-frame plates','mechanical.md','局所修正済み・ケース/Guard未解決'),
'RV-11': R('部品資料、電源換算、USB排他、LED/PCA電圧とI2S記述は訂正済み。購入個体/保持電流/温度・独立OE/遮断・SPK上限は未確認。','P-01/P-03と実ラベルを照合し、EL-09で三系統の実電力を測る。CPU/I2C故障中のPWM残留を想定して独立停止を実配線で検証し、MAX98357AのSD/ゲインを実基板に合わせる。','型番/電源/独立停止/音声基板別の実測表。PM7aで電流を測った扱いにせず、ソフト故障注入を電源遮断保証としない。','ap-004 ap-005 ap-007','cabin-decor head-camera-audio','firmware.md','文書/ソフト修正済み・現物条件待ち'),
'RV-12': R('表示/変換/STL入出力・515ファイル確認を完了し#93はClosed。内壁保持・退化面・旧出力保護の回帰を保存した。','完了を維持する。追加発見の腕Guard原型/左右対応はRV-10とPR-01/A-04で追跡し、その修正後に表示/URDF回帰を追加する。元完了記録の対象範囲を広げない。','既存監査コミットの検証記録と新追跡先。全1898組中99組の体積共有を検査完了と組立合格で混同しない。','','arm plates','stl-export-peer.md','完了（表示/出力/全件記録）'),
'RV-13': R('現行半径78mmの7穴軸は全てHeadTopへ届かず、49候補も後柱とケースが交差。前タブには+3mmカラーを追加済み。','RV-09の軸/ケース確定後に支持数・柱/受け座・開閉を設計する。前タブ増厚に合うねじ長、締結/工具/配線と残肉を照合し、可視面を保つ候補を比較する。','全支持の荷重経路・ねじ長/個数・引抜き/層割れ/開閉試験と旧chassisの補強/再印刷判断。','ap-006','head-camera-audio candidates','mechanical.md','支持候補比較済み・軸確定待ち'),
'RV-14': R('停止でchassis対thigh_cap前約99/133、後405/413mm³が交差。coxa対capとthigh_guardも残り、取付耳だけ削れば直る条件ではない。','RV-09の軸確定後、実C++停止/歩容/遷移でシャーシ・耳・カバーの隙間を比較する。頭支持/電池/ねじ/配線と同時に確認し、可視カバー切削案は先に面積と形を示す。','全到達姿勢の実交差/残肉/支持の記録、RV-16の挿入座と整合、旧印刷品の再使用/加工/再印刷判断。','','leg-shell candidates','simulation.md','交差再現済み・軸確定待ち'),
'RV-15': R('首とTailJoint全長、CabinFront/Eye/Ballの大きい重なりが残る。局所71項目合格の電装室も全体成立ではない。','H-06と首フランジ/通線径/電装取り出し境界を共有し、外形を保つ内側加工・支持・挿入を比較する。RV-07の印刷強度とφ8通線案を同じ形状で評価する。','首/Cabin/Eye/装飾/電装の全体交差と挿入・通線・保守・段階荷重の記録。既存11候補を採用済みとしない。','ap-006','cabin-decor candidates','neck-reinforcement.md','全長交差再現済み・候補未採用'),
'RV-16': R('大腿81.127%/脛77.940%が旧配置で埋没。0.10/0.15mm座は26方向で挿入できず、開放案は可視面切除や脛分離で不採用。','元ガードの見える形状を保ち、殻の分割/着脱/挿入座を比較する。骨格・M3座・工具経路と全挿入軌跡を検査しRV-14の座標と共有する。','閉体だけでなく組立可能な入口/経路・保持/残肉、外観比較と採否。未採用候補をPR-01/PR-05へ量産指示しない。','','leg-shell candidates','guard-seat-candidates.md','6案比較済み・受け座未成立'),
'RV-17': R('片腕のmount/Claw約4.628、Claw/指飾り15.879、指/指飾り17.071mm³が重なる。旧50mm³未満許容を撤回し手内部をNGで記録。','現印刷のペグ/穴を測り、意図した差込/圧入と組立不能を深さ/方向で区別する。隠し座・公差・接着面の候補を左右で比較し、指の外形と到達長を保つ。','全組合せ/全挿入の実形状検査、実ペグ穴/保持/接着記録、旧爪/指/飾りの再使用可否。Guardの原型問題はRV-10へ分離する。Gray/Blackの爪・指・指先は鏡像指定なしの同形複製で、現モデルの左右鏡像と回転/対称性で一致するか実物も確認する。','','arm candidates plates','static-assembly.md','手内部検査済み・嵌合未確認'),
}

CLOSED_KEYS = frozenset({'RV-01', 'RV-02', 'RV-03', 'RV-04', 'RV-12'})

# 完了待ちの辺だけを定義。部品の一部引渡し/同時編集は本文の作業条件で管理する。
DEPENDENCY_UPDATES = {
    'P-05': ['P-04', 'P-02'],
    'PR-01': ['P-02'], 'PR-02': ['P-02'], 'PR-03': ['P-02'],
    'PR-06': ['P-04'],
    'PR-08': ['P-02', 'RV-09', 'RV-13'],
    'PR-10': ['P-07', 'P-02'],
    'EL-04': ['EL-01', 'EL-02', 'EL-03', 'P-03'],
    'EL-07': ['EL-03'],
    'L-01': ['PR-04', 'EL-04', 'P-05'],
    'A-01': ['EL-04', 'P-04', 'RV-17'], 'A-02': ['EL-04', 'P-04', 'RV-17'],
    'A-03': ['A-01', 'A-02', 'L-07', 'EL-06', 'EL-07', 'RV-09', 'RV-10'],
    'H-01': ['EL-04', 'P-04'],
    'H-02': ['P-07', 'PR-10'],
    'H-03': ['PR-07', 'P-02', 'RV-08'],
    'H-04': ['EL-07'],
    'H-05': ['H-03', 'RV-08'],
    'S-01': ['L-06', 'RV-15', 'RV-07'],
    'S-02a': ['L-10', 'RV-06', 'RV-14', 'RV-16'],
    'S-02b': ['L-10', 'RV-06', 'RV-14', 'RV-16'],
    'S-02c': ['L-10', 'RV-06', 'RV-14', 'RV-16'],
    'S-02d': ['L-10', 'RV-06', 'RV-14', 'RV-16'],
    'S-03': ['H-01', 'H-02', 'H-06', 'PR-08', 'L-10', 'RV-09', 'RV-13', 'S-08'],
    'S-05': ['H-06', 'RV-15'],
    'I-01': ['S-03', 'S-04', 'S-06', 'S-07', 'A-04', 'S-02a', 'S-02b', 'S-02c', 'S-02d'],
    'I-02': ['I-01', 'L-10', 'I-08', 'RV-06', 'RV-07'],
    'I-03': ['H-04'],
    'I-07': ['I-02', 'I-03', 'I-04', 'I-05', 'I-06'],
    'RV-05': ['RV-01', 'RV-02', 'RV-03', 'RV-04', 'I-08', 'RV-06', 'RV-07',
              'RV-08', 'RV-09', 'RV-10', 'RV-11', 'RV-12', 'RV-13', 'RV-14',
              'RV-15', 'RV-16', 'RV-17', 'H-06'],
}

TITLE_UPDATES = {
    'P-04': 'P-04 [CAD] 実サーボ寸法を設定へ反映し、再生成・退行検査・印刷影響を記録する',
    'P-05': 'P-05 [要判断] 印刷済み品を部品別に再使用・内部加工・補強・再印刷へ分ける',
    'PR-01': 'PR-01 [印刷] キット灰意匠を不足・嵌合条件別に分離して印刷する',
    'PR-02': 'PR-02 [印刷] 黒いトゥ・指・Insertを部品別の確定条件で印刷する',
    'PR-03': 'PR-03 [印刷] 赤ランプ大4・小4の不足分を透光試験後に用意する',
    'PR-05': 'PR-05 [印刷] 足本体と大腿カバーを別条件で試作・不足数印刷する',
    'PR-06': 'PR-06 [印刷] 首・腕・目・カメラ・音声受けを個別条件で引き渡す',
    'PR-08': 'PR-08 [印刷] 頭の収納・支持確定後にHeadTopの再使用か改訂印刷を判断する',
    'PR-10': 'PR-10 [印刷] 実カメラ版に合うbase・shell・carrierを1組確認する',
    'EL-04': 'EL-04 [電装] 実サーボを1個ずつ校正し、20駆動軸と予備を識別する',
    'EL-07': 'EL-07 [ファーム] 通常版を無負荷ベンチで確認し、初期脱力・出力方向を検証する',
    'EL-09': 'EL-09 [要判断] 実電源の電圧・電流・温度から継続か交換を決める',
    'L-06': 'L-06 [組立] 頭無し試験用シャーシ・ヨーサーボ・仮電装を組む',
    'A-04': 'A-04 [仕上げ] 腕殻の改訂配置とGuard原型・左右対応を確認して固定する',
    'H-04': 'H-04 [電装] 裸配線のI2S音声をmock・PTT・低音量再生でベンチ確認する',
    'H-05': 'H-05 [組立] 改訂Mouth一式の挿入・小キー公差・配線を確認する',
    'H-07': 'H-07 [要判断] CH_HEAD/ch12を予備・未接続として実物確認する',
    'S-05': 'S-05 [仕上げ] Cabinの電装室・接合・目座が確定した部品を組む',
    'S-06': 'S-06 [組立] 採用した首とCabinの支持・締結・通線を実物で確認する',
    'S-08': 'S-08 [要判断] 頭Insert・Screwの位置と受け座・挿入経路を照合する',
    'I-01': 'I-01 [測定] 全装備の実重量・支持荷重・重心を測りモデルへ反映する',
    'I-08': 'I-08 [検証] 実購入個体の照合後に物理モデル・自己干渉・材料別接触を再評価する',
    'RV-08': 'RV-08 [機構不具合] 修正済みMouth挿入路に残る小キー公差・実保持を確定する',
    'RV-10': 'RV-10 [機構不具合] 肩と前脚のケース干渉・腕Guardの原型対応を解消する',
}

# 監査コミットの固定リンクは履歴として変更しない。
PUBLISHED_EVIDENCE = {'I-08': [('監査コミット 0de7154',
           'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
          ('物理監査報告',
           'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/simulation.md'),
          ('全89条件・18姿勢の確認記録',
           'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/simulation/final_refresh_evidence.json'),
          ('16回帰と実C++照合',
           'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/simulation-regression.log')],
 'E9': [('監査コミット 0de7154',
         'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
        ('監査総括',
         'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/README.md'),
        ('23検査の実行結果',
         'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/verify-results.json'),
        ('製作への影響',
         'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/manufacturing.md')],
 'RV-01': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('制御・音声の再現と修正',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/firmware.md'),
           ('ホスト実行と通常・校正ビルド',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/firmware-host-and-build.log'),
           ('出力照合を含む物理用回帰',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/simulation-regression.log')],
 'RV-02': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('製作への影響と再使用判断',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/manufacturing.md'),
           ('原型・3MF・旧媒体の保持記録',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/manufacturing-preservation.json'),
           ('生成・比較処理の回帰ログ',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/regression.log')],
 'RV-03': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('検査基盤の独立レビューと再現',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/integration-peer-review.md'),
           ('負例を含む回帰ログ',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/regression.log'),
           ('最終23検査と終了判定',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/verify-results.json')],
 'RV-04': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('親子・依存の全件照合',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/github-relations-final.json'),
           ('既存Statusの保持',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/project-status-preservation.json'),
           ('Issue・記録処理の回帰ログ',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/issue-and-coverage-final-regression.log')],
 'RV-05': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('監査総括',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/README.md'),
           ('最終検査結果',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/verify-results.json'),
           ('物理計算の最終確認',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/simulation/final_refresh_evidence.json')],
 'RV-08': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('口・シャーシの検査',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/check_mouth_chassis.json'),
           ('製作への変更',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/manufacturing.md'),
           ('残る固定部品の分類',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/static-intersection-final-triage.json')],
 'RV-10': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('機構の修正と残件',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/mechanical.md'),
           ('coxaポケットの独立評価',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/coxa-pocket-peer.md'),
           ('変更した印刷部品',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/manufacturing.md')],
 'RV-11': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('配線と基板別条件',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/wiring.md'),
           ('購入品・測定器の訂正',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/shopping.md'),
           ('電源計算の未検証項目',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/power-budget.json'),
           ('制御・音声の検証',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/firmware.md')],
 'RV-12': [('監査コミット 0de7154',
            'https://github.com/hapx2yuki/Tachikoma/commit/0de71547c1af59abc6bcc3484b03b12e9430df2b'),
           ('検査対象と確認方法の全件台帳',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/coverage-complete.json'),
           ('STL出力の独立検証',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/stl-export-peer.md'),
           ('出力・変換・検査器の回帰ログ',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/final-geometry/verify/regression.log'),
           ('固定組立の未解決分類',
            'https://github.com/hapx2yuki/Tachikoma/blob/0de71547c1af59abc6bcc3484b03b12e9430df2b/docs/audits/20260905-round2/static-assembly.md')]}

DEPENDENCY_REASONS = {
    'P-05': '実測差分だけでなく、現物の使用版/印刷設定の照合を再使用判断の前提に追加。',
    'PR-01': '灰一式の即印刷を撤回。まず実在庫と版を確認し、部品ごとの未解決条件で分離。',
    'PR-02': '黒一式の即印刷を撤回。150%toeと指/Insertの実在庫・用途を確認して分離。',
    'PR-03': '赤ランプも現物不足を確定して重複印刷を避ける。独立した透光見本は先行可能。',
    'PR-06': 'Restの首/眼/カメラ待ちを全品へ波及させない。各部品の実測/設計合格を受入側で確認する。',
    'PR-08': 'ケース収納だけでは頭が固定できないため、頭支持RV-13の確定を追加。',
    'PR-10': '旧カメラbaseを無条件再印刷せず、現センサー版と既印刷品を確認する。',
    'EL-04': '許容電圧/型番の未同定サーボへ一律6Vを投入しないため実測P-03を追加。',
    'EL-07': '無負荷の通常ファーム検証は全機CAD更新を待たない。本体の荷重試験はL-09に残す。',
    'L-01': '足1個の検品は必要だが、大腿カバー4個を含むPR-05全体の完了はFLベンチに不要。',
    'A-01': '右腕の個別部品受入れへ変更。混載印刷/本体ケース問題を単体腕へ広げず、実測をCADに反映するP-04を直接追加し、固定手RV-17を維持。',
    'A-02': '左腕も個別部品受入れへ変更。実測のCAD反映P-04を直接追加し、先行_L在庫の確認と固定手RV-17を完了条件に残す。',
    'A-03': '本体へ吊る時は実脚が必要。L-06をL-07へ進め、実干渉のある軸配置RV-09/肩ケースRV-10を追加。',
    'H-01': '眼の受けだけを引渡し、首/腕/カメラ全体待ちを解除。実測を受けへ反映するP-04を直接追加し、頭への接着はS-03で制御。',
    'H-02': 'カメラ1組に無関係なRest全体の完了を不要化。現センサーとカメラ部品の確認は維持。',
    'H-03': '音声受け1個の検品へ分離し、Restの首/眼待ちを解除。音声実測/改訂口/旧品照合は維持。',
    'H-04': 'I2S裸ベンチを砲身組込の完了待ちから分離。組込後音響はH-03/S-04で再確認。',
    'H-05': '必要なCap/Key/Pegだけを個別受入れし、灰一式印刷の完了待ちを解除。小キー公差RV-08は維持。',
    'S-01': '採用した首部品の受入れへ変更。腕/眼/灰小物全体待ちは不要、首全体成立/強度は維持。',
    'S-02a': 'FLに必要な部品行を個別受入れ。灰/黒/大腿混載プレート完了は不要、歩行/支持/カバー/ガードの設計条件は維持。',
    'S-02b': 'FR鏡像の個別部品受入れへ変更。歩行/支持/カバー/ガードの成立を維持。',
    'S-02c': 'RL鏡像の個別部品受入れへ変更。歩行/支持/カバー/ガードの成立を維持。',
    'S-02d': 'RR標準の個別部品受入れへ変更。歩行/支持/カバー/ガードの成立を維持。',
    'S-03': '頭に必要な装飾だけを受入れ、灰/黒一式を待たない。実測ラベル付きInsert/Screwにも交差があるためS-08の受け座/挿入成立を追加し、眼/カメラ/電装/収納/支持を維持。',
    'S-05': 'Cabin用の不足意匠を個別受入れし、手や脚を含む色別一式待ちを解除。電装室/首全体の成立は必須。',
    'I-01': '完成重量から漏れていたMouth取付とLED/DFPlayer/配線を追加。',
    'I-02': '頭無し歩行と購入個体反映後の物理検証を明示的な前提に追加。足支持/印刷強度は維持。',
    'I-03': '裸音声の実ネットワーク/API往復は頭/Mouth組立を待たない。装着後試験はS-04へ残す。',
    'I-07': 'カメラ連携と実物知見の文書反映も完成紹介の前提として明示。',
    'RV-05': '全体判定から欠けていた足支持RV-06と印刷強度RV-07を追加。',
}

# 完成後の外装/演出は同じ本体を扱う。部品単体の下処理は本文の範囲で並行可能。
BODY_RESOURCE_KEYS = frozenset({'A-04', 'S-02a', 'S-02b', 'S-02c', 'S-02d', 'I-05'})

# 追加購入台帳との作業別対応（2026-09-05）。型番/数量の正は台帳、ここは課題からの参照。
PURCHASE_REFERENCES = {'E1': ['ap-001', 'ap-002', 'ap-003', 'ap-004', 'ap-094'],
 'E2': ['ap-120', 'ap-125', 'ap-126', 'ap-128'],
 'E3': ['ap-004', 'ap-007', 'ap-009', 'ap-028', 'ap-030', 'ap-031'],
 'E4': ['ap-004', 'ap-008', 'ap-020', 'ap-125'],
 'E5': ['ap-021', 'ap-025', 'ap-073', 'ap-083'],
 'E6': ['ap-022', 'ap-054', 'ap-055', 'ap-056', 'ap-059'],
 'E7': ['ap-006', 'ap-071', 'ap-077', 'ap-083', 'ap-087'],
 'E8': ['ap-004', 'ap-010', 'ap-011', 'ap-012'],
 'E9': ['ap-004', 'ap-007', 'ap-094'],
 'P-01': ['ap-001', 'ap-002', 'ap-003', 'ap-004', 'ap-005', 'ap-006', 'ap-007'],
 'P-02': ['ap-094', 'ap-116', 'ap-128'],
 'P-03': ['ap-020', 'ap-021', 'ap-022', 'ap-024', 'ap-025', 'ap-026', 'ap-094'],
 'P-04': ['ap-094'],
 'P-05': ['ap-003', 'ap-093', 'ap-100', 'ap-101', 'ap-106'],
 'P-06': ['ap-054', 'ap-055', 'ap-056', 'ap-057', 'ap-058', 'ap-094'],
 'P-07': ['ap-017', 'ap-059', 'ap-060', 'ap-064', 'ap-094'],
 'P-08': [],
 'PR-01': ['ap-121', 'ap-129', 'ap-083', 'ap-106'],
 'PR-02': ['ap-122', 'ap-106'],
 'PR-03': ['ap-123', 'ap-124'],
 'PR-04': ['ap-125', 'ap-128'],
 'PR-05': ['ap-121', 'ap-129', 'ap-126', 'ap-127', 'ap-128'],
 'PR-06': ['ap-120', 'ap-125', 'ap-128'],
 'PR-07': ['ap-120', 'ap-094'],
 'PR-08': ['ap-120', 'ap-006', 'ap-087'],
 'PR-09': ['ap-003', 'ap-006', 'ap-125', 'ap-128'],
 'PR-10': ['ap-059', 'ap-060', 'ap-120', 'ap-135'],
 'PR-11': ['ap-125', 'ap-128'],
 'EL-01': ['ap-009',
           'ap-013',
           'ap-029',
           'ap-030',
           'ap-031',
           'ap-036',
           'ap-037',
           'ap-038',
           'ap-039',
           'ap-040',
           'ap-041',
           'ap-042',
           'ap-043',
           'ap-046',
           'ap-048',
           'ap-049'],
 'EL-02': ['ap-001', 'ap-002', 'ap-007', 'ap-009', 'ap-028', 'ap-053'],
 'EL-03': ['ap-007', 'ap-009', 'ap-012', 'ap-016', 'ap-027', 'ap-063'],
 'EL-04': ['ap-004', 'ap-008', 'ap-013', 'ap-020', 'ap-021', 'ap-022', 'ap-114'],
 'EL-05': ['ap-041', 'ap-042', 'ap-043', 'ap-044', 'ap-046', 'ap-047', 'ap-086', 'ap-099', 'ap-118'],
 'EL-06': ['ap-043', 'ap-044', 'ap-046', 'ap-047', 'ap-086', 'ap-088', 'ap-118'],
 'EL-07': ['ap-007', 'ap-008', 'ap-012', 'ap-016', 'ap-027', 'ap-063'],
 'EL-08': ['ap-005', 'ap-014', 'ap-032', 'ap-033', 'ap-034', 'ap-035', 'ap-050', 'ap-051', 'ap-052', 'ap-053'],
 'EL-09': ['ap-004', 'ap-007', 'ap-009', 'ap-010', 'ap-012', 'ap-030', 'ap-031', 'ap-036', 'ap-037', 'ap-038'],
 'EL-10': ['ap-004', 'ap-007', 'ap-008', 'ap-010'],
 'L-01': ['ap-020', 'ap-024', 'ap-070', 'ap-072', 'ap-075', 'ap-101'],
 'L-02': ['ap-004', 'ap-007', 'ap-010', 'ap-013', 'ap-143'],
 'L-03': ['ap-020', 'ap-024', 'ap-070', 'ap-075'],
 'L-04': ['ap-020', 'ap-024', 'ap-070', 'ap-075'],
 'L-05': ['ap-020', 'ap-024', 'ap-070', 'ap-075'],
 'L-06': ['ap-001', 'ap-002', 'ap-007', 'ap-028', 'ap-080', 'ap-081'],
 'L-07': ['ap-020', 'ap-024', 'ap-070', 'ap-075'],
 'L-08': ['ap-044', 'ap-046', 'ap-047', 'ap-081', 'ap-082', 'ap-088'],
 'L-09': ['ap-004', 'ap-007', 'ap-008', 'ap-009', 'ap-010'],
 'L-10': ['ap-004', 'ap-007', 'ap-008', 'ap-010', 'ap-081'],
 'L-11': ['ap-004', 'ap-010', 'ap-013', 'ap-020', 'ap-130', 'ap-143'],
 'A-01': ['ap-021', 'ap-025', 'ap-073', 'ap-075', 'ap-083'],
 'A-02': ['ap-021', 'ap-025', 'ap-073', 'ap-075', 'ap-083'],
 'A-03': ['ap-021', 'ap-025', 'ap-073', 'ap-075'],
 'A-04': ['ap-073', 'ap-083', 'ap-088'],
 'H-01': ['ap-022', 'ap-026', 'ap-079', 'ap-083', 'ap-092'],
 'H-02': ['ap-017', 'ap-059', 'ap-060', 'ap-064', 'ap-135', 'ap-139'],
 'H-03': ['ap-054', 'ap-056', 'ap-057', 'ap-058', 'ap-084'],
 'H-04': ['ap-009', 'ap-015', 'ap-045', 'ap-054', 'ap-055', 'ap-056'],
 'H-05': ['ap-083', 'ap-094'],
 'H-06': ['ap-001', 'ap-002', 'ap-027', 'ap-028', 'ap-030', 'ap-031', 'ap-053', 'ap-138'],
 'H-07': ['ap-006', 'ap-087'],
 'S-01': ['ap-071', 'ap-077', 'ap-083', 'ap-088'],
 'S-02a': ['ap-076', 'ap-078', 'ap-083', 'ap-126', 'ap-140'],
 'S-02b': ['ap-076', 'ap-078', 'ap-083', 'ap-126', 'ap-140'],
 'S-02c': ['ap-076', 'ap-078', 'ap-083', 'ap-126', 'ap-140'],
 'S-02d': ['ap-076', 'ap-078', 'ap-083', 'ap-126', 'ap-140'],
 'S-03': ['ap-006', 'ap-083', 'ap-087', 'ap-088'],
 'S-04': ['ap-054', 'ap-056', 'ap-057', 'ap-058', 'ap-083'],
 'S-05': ['ap-033', 'ap-083', 'ap-085', 'ap-106'],
 'S-06': ['ap-071', 'ap-077', 'ap-138'],
 'S-07': ['ap-005', 'ap-032', 'ap-033', 'ap-034', 'ap-035', 'ap-052', 'ap-085'],
 'S-08': ['ap-083', 'ap-094'],
 'I-01': ['ap-011'],
 'I-02': ['ap-004', 'ap-007', 'ap-008', 'ap-010'],
 'I-03': ['ap-054', 'ap-055', 'ap-056'],
 'I-04': ['ap-017', 'ap-059', 'ap-064'],
 'I-05': ['ap-021', 'ap-022', 'ap-033', 'ap-034'],
 'I-06': [],
 'I-07': [],
 'I-08': ['ap-004', 'ap-010', 'ap-011', 'ap-012'],
 'RV-01': ['ap-007'],
 'RV-02': ['ap-116'],
 'RV-03': [],
 'RV-04': [],
 'RV-05': ['ap-004', 'ap-007', 'ap-010', 'ap-094'],
 'RV-06': ['ap-126', 'ap-127', 'ap-140'],
 'RV-07': ['ap-010', 'ap-011', 'ap-125', 'ap-126', 'ap-143'],
 'RV-08': ['ap-054', 'ap-055', 'ap-056', 'ap-057', 'ap-058', 'ap-094'],
 'RV-09': ['ap-020', 'ap-021', 'ap-022', 'ap-059', 'ap-094'],
 'RV-10': ['ap-021', 'ap-025', 'ap-094'],
 'RV-11': ['ap-004', 'ap-007', 'ap-009', 'ap-030', 'ap-031', 'ap-036', 'ap-052'],
 'RV-12': [],
 'RV-13': ['ap-006', 'ap-070', 'ap-087'],
 'RV-14': ['ap-094', 'ap-125'],
 'RV-15': ['ap-071', 'ap-077', 'ap-088', 'ap-138'],
 'RV-16': ['ap-083', 'ap-094'],
 'RV-17': ['ap-083', 'ap-094']}

PURCHASE_LABELS = {'ap-001': 'PCA9685用スタンドオフ',
 'ap-002': 'PCA9685上段なべ小ねじ',
 'ap-003': 'φ2.2 mmドリル刃',
 'ap-004': 'DCクランプ電流計',
 'ap-005': 'DFPlayer用microSD',
 'ap-006': '前90度タブ増厚分のねじ',
 'ap-007': 'CPUから独立した停止・電源遮断',
 'ap-008': '無負荷試験の機体支持台',
 'ap-009': '電圧/抵抗/導通テスター',
 'ap-010': '表面温度測定手段',
 'ap-011': '質量測定用はかり',
 'ap-012': '瞬間電圧/PWM記録の計器',
 'ap-013': '試験用電流制限電源',
 'ap-014': 'microSD読取手段',
 'ap-015': 'AWG30の被覆処理手段',
 'ap-016': '本体USBデータケーブル',
 'ap-017': 'XIAO用USB-Cデータケーブル',
 'ap-020': '脚サーボ',
 'ap-021': '腕サーボMG90S',
 'ap-022': '目用サブマイクロサーボ',
 'ap-024': '脚付属ホーン/中心ねじ',
 'ap-025': '腕付属ホーン/中心ねじ',
 'ap-026': '目付属ホーン/中心ねじ',
 'ap-027': '本体ESP32開発ボード',
 'ap-028': 'PCA9685基板',
 'ap-029': '2S LiPo電池',
 'ap-030': '6 Vサーボ用UBEC',
 'ap-031': '5 Vロジック用DC-DC',
 'ap-032': 'LED信号レベル変換IC',
 'ap-033': 'WS2812B',
 'ap-034': 'DFPlayer Mini',
 'ap-035': 'DFPlayer用ボディスピーカー',
 'ap-036': 'メインスイッチ',
 'ap-037': 'ヒューズホルダー',
 'ap-038': 'ヒューズ',
 'ap-039': 'サーボ電源電解コンデンサ',
 'ap-040': '5 V電源電解コンデンサ',
 'ap-041': 'XT60コネクタ',
 'ap-042': 'AWG16線',
 'ap-043': 'AWG20線',
 'ap-044': 'AWG26線',
 'ap-045': 'AWG30線',
 'ap-046': 'サーボ電源外部分配部材',
 'ap-047': 'サーボ延長/中継配線',
 'ap-048': 'VBAT分圧抵抗',
 'ap-049': 'VBAT分圧抵抗',
 'ap-050': 'DFPlayer RX直列抵抗',
 'ap-051': 'WS2812 DIN直列抵抗',
 'ap-052': '74AHCT125用バイパスコンデンサ',
 'ap-053': '基板実装/ヘッダー/絶縁基材',
 'ap-054': 'INMP441マイク',
 'ap-055': 'MAX98357Aアンプ',
 'ap-056': '口内薄型スピーカー',
 'ap-057': '音声2ピンコネクタ',
 'ap-058': '音声6ピンコネクタ',
 'ap-059': 'XIAO ESP32S3 Sense',
 'ap-060': 'カメラFPC延長',
 'ap-063': 'USB時の外部5 V切離し',
 'ap-064': 'XIAOアンテナ',
 'ap-070': 'M3×10タッピング',
 'ap-071': '首先端のなべ小ねじ',
 'ap-072': '脚ホーン中心用交換ねじ',
 'ap-073': 'M2×8タッピング',
 'ap-075': 'M2.6×8タッピング',
 'ap-076': 'M3×40なべ小ねじ',
 'ap-077': '首先端M3ナット',
 'ap-078': 'M3ナイロンロックナット',
 'ap-079': '目ホーン用M1.7×6級',
 'ap-080': '電池固定バンド',
 'ap-081': '結束/非導電ストラップ',
 'ap-082': 'スパイラルチューブ',
 'ap-083': '構造/意匠接着剤',
 'ap-084': 'グルースティック',
 'ap-085': '両面テープ',
 'ap-086': '熱収縮チューブ/絶縁材',
 'ap-087': '頭部支持の座金/スペーサー',
 'ap-088': '線材引出し保護/引張止め',
 'ap-092': 'φ1.1 mmドリル',
 'ap-093': 'φ2.8 mmドリル',
 'ap-094': 'ノギス',
 'ap-099': 'AWG16/20/26用ストリッパー',
 'ap-100': 'ニッパー/ペンチ',
 'ap-101': 'バイス/クランプ',
 'ap-106': 'ヤスリ/ペーパー',
 'ap-114': '水準器/水平確認手段',
 'ap-116': '部品表示用マーカー',
 'ap-118': '端子圧着工具',
 'ap-120': '青PLA',
 'ap-121': '灰PLA',
 'ap-122': '黒PLA',
 'ap-123': '白PLA',
 'ap-124': '赤PLA',
 'ap-125': '構造用PETG',
 'ap-126': '黒TPU95A',
 'ap-127': 'TPU外部供給保持具',
 'ap-128': '材料乾燥/保管手段',
 'ap-129': '灰PLA(Amazon購入記録)',
 'ap-130': '脚サーボの上位交換',
 'ap-135': 'カメラ/レンズ交換',
 'ap-138': 'Cabin棚候補のねじ',
 'ap-139': 'XIAO候補の固定材',
 'ap-140': 'TPU靴候補の接着材',
 'ap-143': '片脚荷重試験の重り'}

assert set(PURCHASE_REFERENCES) == set(REVIEW)
for _key, _anchors in PURCHASE_REFERENCES.items():
    REVIEW[_key]['purchase'] = _anchors
