#pragma once
// GENERATED by tools/generate_print_first_profile.py; do not edit.
// source: hardware/src/config.py#PRINT_FIRST_GAIT sha256=76edae8c753bca26cef6bbfd392c867f57e3f1274215960dab9497b967248b95
// This header is used only when TACHIKOMA_PRINT_FIRST_PROFILE=1.
constexpr bool PRINT_FIRST_PROFILE_ADOPTED = false;
constexpr const char* PRINT_FIRST_PROFILE_STATUS = "CANDIDATE_NOT_ADOPTED";
constexpr float PRINT_FIRST_BODY_H = 115.000000f;
constexpr float PRINT_FIRST_STANCE_R = 105.000000f;
constexpr float PRINT_FIRST_STANCE_OFF_X = 0.000000f;
constexpr float PRINT_FIRST_STANCE_OFF_Y = -30.000000f;
constexpr float PRINT_FIRST_STEP_H = 8.000000f;
constexpr float PRINT_FIRST_MAX_STEP = 18.000000f;
constexpr float PRINT_FIRST_MAX_TURN_DEG = 12.000000f;
constexpr float PRINT_FIRST_CYCLE_T = 2.400000f;
constexpr float PRINT_FIRST_DUTY = 0.900000f;
constexpr float PRINT_FIRST_SWAY_MM[4] = {28.900000f, 28.900000f, 34.000000f, 34.000000f};
constexpr float PRINT_FIRST_SWAY_LEAD = 0.110000f;
constexpr float PRINT_FIRST_PHASE_OFF[4] = {0.250000f, 0.500000f, 0.750000f, 0.000000f};
constexpr float PRINT_FIRST_ARM_SWING_DEG = 0.000000f;
constexpr float PRINT_FIRST_HIP_R = 85.000000f;
constexpr float PRINT_FIRST_LEG_ORIGIN[4][2] = {
    {82.103695f, 21.999619f},
    {-82.103695f, 21.999619f},
    {-73.612159f, -42.500000f},
    {73.612159f, -42.500000f},
};
