#!/usr/bin/env python3
"""config.py の PRINT_FIRST_GAIT から print-first 用ヘッダーを生成する。

通常の ``config.h`` は変更せず、PlatformIO の print-first 環境だけが
``TACHIKOMA_PRINT_FIRST_PROFILE=1`` でこのヘッダーを参照する。値を手で
同期したテストにせず、生成元の辞書を毎回読み直す。
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'hardware/src'))
import config as C

OUTPUT=ROOT/'firmware/src/print_first_gait.h'


def _checked_output(path: Path) -> Path:
    """Accept only a repository path, while retaining the internal default."""
    candidate = Path(path)
    if (".." in candidate.parts or "\x00" in str(candidate)
            or "\\" in str(candidate) or str(candidate).startswith("~")):
        raise ValueError("--output must be a repository-relative path")
    if not candidate.is_absolute():
        candidate = ROOT / candidate
    if candidate.is_symlink():
        raise ValueError("--output symlink is not permitted")
    resolved = candidate.resolve(strict=False)
    if not resolved.is_relative_to(ROOT):
        raise ValueError("--output must stay inside repository")
    return resolved


def public_path(path):
    return _checked_output(Path(path)).relative_to(ROOT).as_posix()


def _f(value):
    return f'{float(value):.6f}f'


def generate(output=OUTPUT):
    cfg=C.PRINT_FIRST_GAIT
    required=('body_h','stance_r','stance_off_xy','step_h','max_step','max_turn_deg',
              'cycle_t','duty','sway_mm','sway_lead','phase_off','arm_swing_deg','hip_r',
              'status','adopted')
    missing=[key for key in required if key not in cfg]
    if missing:raise ValueError(f'PRINT_FIRST_GAIT missing keys: {missing}')
    if len(cfg['sway_mm'])!=4 or len(cfg['phase_off'])!=4 or len(C.LEG_ANGLES)!=4:
        raise ValueError('PRINT_FIRST_GAIT arrays must have four legs')
    off=cfg['stance_off_xy'];legs=('FR','FL','RL','RR')
    origins=[(float(cfg['hip_r'])*C._math.cos(C._math.radians(C.LEG_ANGLES[leg])),
              float(cfg['hip_r'])*C._math.sin(C._math.radians(C.LEG_ANGLES[leg]))) for leg in legs]
    source=ROOT/'hardware/src/config.py'
    source_sha=hashlib.sha256(source.read_bytes()).hexdigest()
    lines=[
        '#pragma once',
        '// GENERATED by tools/generate_print_first_profile.py; do not edit.',
        f'// source: hardware/src/config.py#PRINT_FIRST_GAIT sha256={source_sha}',
        '// This header is used only when TACHIKOMA_PRINT_FIRST_PROFILE=1.',
        f'constexpr bool PRINT_FIRST_PROFILE_ADOPTED = {"true" if cfg["adopted"] else "false"};',
        f'constexpr const char* PRINT_FIRST_PROFILE_STATUS = "{cfg["status"]}";',
        f'constexpr float PRINT_FIRST_BODY_H = {_f(cfg["body_h"])};',
        f'constexpr float PRINT_FIRST_STANCE_R = {_f(cfg["stance_r"])};',
        f'constexpr float PRINT_FIRST_STANCE_OFF_X = {_f(off[0])};',
        f'constexpr float PRINT_FIRST_STANCE_OFF_Y = {_f(off[1])};',
        f'constexpr float PRINT_FIRST_STEP_H = {_f(cfg["step_h"])};',
        f'constexpr float PRINT_FIRST_MAX_STEP = {_f(cfg["max_step"])};',
        f'constexpr float PRINT_FIRST_MAX_TURN_DEG = {_f(cfg["max_turn_deg"])};',
        f'constexpr float PRINT_FIRST_CYCLE_T = {_f(cfg["cycle_t"])};',
        f'constexpr float PRINT_FIRST_DUTY = {_f(cfg["duty"])};',
        f'constexpr float PRINT_FIRST_SWAY_MM[4] = {{{", ".join(_f(v) for v in cfg["sway_mm"])}}};',
        f'constexpr float PRINT_FIRST_SWAY_LEAD = {_f(cfg["sway_lead"])};',
        f'constexpr float PRINT_FIRST_PHASE_OFF[4] = {{{", ".join(_f(v) for v in cfg["phase_off"])}}};',
        f'constexpr float PRINT_FIRST_ARM_SWING_DEG = {_f(cfg["arm_swing_deg"])};',
        f'constexpr float PRINT_FIRST_HIP_R = {_f(cfg["hip_r"])};',
        'constexpr float PRINT_FIRST_LEG_ORIGIN[4][2] = {',
        *[f'    {{{_f(x)}, {_f(y)}}},' for x,y in origins],
        '};',
        '',
    ]
    output=_checked_output(Path(output));output.parent.mkdir(parents=True,exist_ok=True)
    output.write_text('\n'.join(lines),encoding='utf-8')
    return {'path':public_path(output),'exists':True,
            'sha256':hashlib.sha256(output.read_bytes()).hexdigest(),
            'source':'hardware/src/config.py#PRINT_FIRST_GAIT','source_sha256':source_sha,
            'status':cfg['status'],'adopted':bool(cfg['adopted'])}


def main():
    ap=argparse.ArgumentParser();ap.add_argument('--output',type=Path,default=None)
    args=ap.parse_args()
    output=OUTPUT
    if args.output is not None:
        if args.output.is_absolute() or '..' in args.output.parts:
            ap.error('--output must be a repository-relative path')
        output=ROOT/args.output
    print(json.dumps(generate(output), ensure_ascii=False, indent=2, allow_nan=False))


if __name__=='__main__':main()
